### ISSUE TITLE
install.py issue Failing...

### ISSUE THREAD

**Issue by TechXero** [catppuccin/gtk#102]
**Describe the bug**

After running the command 
`python install.py mocha -l -a mauve --tweaks normal -d ~/.themes`

I get following error
```
Traceback (most recent call last):
  File "/home/xero/Documents/catppuccin/gtk/install.py", line 12, in <module>
    from scripts.ctp_colors import ctp_colors, get_all_accent
  File "/home/xero/Documents/catppuccin/gtk/scripts/ctp_colors.py", line 1, in <module>
    from catppuccin import Flavour
ModuleNotFoundError: No module named 'catppuccin'
```

**Mention your distribution and your theme version**
ArchLinux latest updates applied

**Select how you installed the theme**
- [ ] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [ X ] Using the python install script 
`python install.py mocha -l -a mauve --tweaks normal -d ~/.themes`
- [ ] Flatpak

**Expected behavior**
For it to work what else ?

**Comment by ghostx31** [comment]
You're missing the catppuccin python package. Install it by running `pip install catppuccin`.

**Comment by TechXero** [comment]
> You're missing the catppuccin python package. Install it by running `pip install catppuccin`.

running this command gives me 
```
[xero@xero-ricer gtk]$ pip install catppuccin
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try 'pacman -S
    python-xyz', where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Arch-packaged Python package,
    create a virtual environment using 'python -m venv path/to/venv'.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip.
    
    If you wish to install a non-Arch packaged Python application,
    it may be easiest to use 'pipx install xyz', which will manage a
    virtual environment for you. Make sure you have python-pipx
    installed via pacman.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
```

**Comment by ghostx31** [comment]
Alright, this is something new from pip's side. 
In the gtk repository's root directory, run `python -m venv .` to create a virtual env. Then enable it by running `source bin/activate`. Then run `pip install catppuccin`.

**Comment by TechXero** [comment]
@ghostx31 

> python -m venv

Or install `python-catppuccin` from AUR ...

**Comment by ghostx31** [comment]
Yeah, that exists too if you find that convenient.

**Comment by TechXero** [comment]
Success ! Thanks I scripted it too now rice can be applied by anyone on my distro..
![XeroCat](https://i.imgur.com/I5MayRg.png)
