### ISSUE TITLE
Missing theme for many legacy applications

### ISSUE THREAD

**Issue by shans10** [catppuccin/gtk#106]
**Describe the bug**
Setting the theme for **Legacy Applications** from `gnome-tweaks` **does not work with many applications such as gnome-tweaks, dconf-editor, gnome-disks, geary, system-monitor** while **it works with gnome-terminal, firefox and google-chrome**. I tried Colloid theme and it works with all these applications.

**Mention your distribution and your theme version**
**Distribution**: OpenSUSE Tumbleweed
**Gnome version**: 44.2
**Theme version**: v0.6.1

**Select how you installed the theme**
- [x] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [x] Using the python install script - `python install.py mocha -a blue --tweaks rimless`
- [ ] Flatpak

I tried both of the above methods to install the theme.

**Symlinked the gtk-4.0 folder?**
Yes, I have symlinked the gtk-4.0 folder as mentioned in the README and all gtk-4 applications are working fine with the theme.

**Expected behavior**
The theme should work with all legacy applications

**Screenshots**

![Screenshot from 2023-07-11 13-42-55](https://github.com/catppuccin/gtk/assets/28944997/9134fba1-1c0d-4750-b268-52fbccb94773)
![Screenshot from 2023-07-11 13-37-09](https://github.com/catppuccin/gtk/assets/28944997/b7d020b8-7084-4ca4-8249-297881e918fb)
![Screenshot from 2023-07-11 13-37-29](https://github.com/catppuccin/gtk/assets/28944997/e85df833-edc6-4897-9f40-16aaf5c0b48c)
![Screenshot from 2023-07-11 13-37-02](https://github.com/catppuccin/gtk/assets/28944997/c5780c4c-2126-40ae-a6d0-353cce109a2d)

**Comment by azu0609** [comment]
Renaming Catppuccin-\*-dark to Catppuccin-*-Dark seems to fix the issue

**Comment by shans10** [comment]
> Renaming Catppuccin-*-dark to Catppuccin-*-Dark seems to fix the issue

Strange that indeed does work, thank you for the solution :)

**Comment by thekoma** [comment]
I still have this problem even after renaming. I've also tried copying and using .themes instead of AUR.

**Comment by thekoma** [comment]
[themesfolder.tar.gz](https://github.com/catppuccin/gtk/files/12143405/themesfolder.tar.gz)
You can find attached the .themes folder I'm using
I'm full updated on Archlinux on gnome. No aur involved.
I've tried the aur packages but the results are the same.

**Comment by shans10** [comment]
> 

Try deleting the old folders and just keep the renamed ones with `Catppuccin-*-Dark` . Maybe the issue is due to both versions being there in the themes folder also check you are setting the theme to the renamed ones and not the original in gnome-tweaks.
