### ISSUE TITLE
White border on GTK3 apps ?

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [catppuccin/gtk#107]
**Describe the bug**
As shown, for some weird reason, the GTK3 theme version of the theme, is using "light" colors on some buttons borders and most annoyingly, on GTK3 titlebars for some weird reason.
Here, is the AWF test application in GTK4 at the right, GTK3 at the left, and gnome-terminal (so GTK3) to showcase the titlebar issue.

**Mention your distribution and your theme version**
Fedora 38

**Select how you installed the theme**
- [ ] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [✓] Using the python install script 
```
git pull --recurse-submodules
source venv/bin/activate  
python3 install.py frappe -a lavender -l --tweaks normal
```
I also renamed the theme to fix #106 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Yes.

**Expected behavior**
To have the GTK3 theme not use those light accent as the GTK4 theme.

**Screenshots**
![image](https://github.com/catppuccin/gtk/assets/13170204/70040b33-0b7c-4614-94fa-1fe46d5e1d2e)

**Additional context**
My main used theme folder is user-located, at `~/.local/share/themes`. `~/.themes` is just a symlink to that folder.

**Comment by PoorPocketsMcNewHold** [comment]
An update on that, this seems to be using a sort of light theming, despite being a dark theme *(and being compiled as one dark theme)*. 
Appending 
```
[Settings]
gtk-application-prefer-dark-theme=true
```
 In the gtk-3-0 config folder, settings.ini file, doesn't change anything.

**Comment by rubyowo** [comment]
Hi! Can you please report if newer versions have fixed this issue?

**Comment by sgoudham** [comment]
Closing as issue has gone stale with no responses from authors. 

The latest release at the time of writing is https://github.com/catppuccin/gtk/releases/tag/v0.7.4. It'd be appreciated if someone could confirm if this issue is fixed in that release.

Thanks!
