### ISSUE TITLE
GTK2 unapplied color accent

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [catppuccin/gtk#108]
**Describe the bug**
As shown, the GTK2 theming doesn't have any applied color accent despite specifically stated in the python installing script, and working fine on GTK4 & GTK3 themes.
Here, is the AWF test application in GTK4 at the right, GTK2 at the left.

**Mention your distribution and your theme version**
Fedora 38

**Select how you installed the theme**
- [ ] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [✓] Using the python install script 
```
git pull --recurse-submodules
source venv/bin/activate  
python3 install.py frappe -a lavender -l --tweaks normal
```
I also renamed the theme to fix #106 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Yes.

**Expected behavior**
To have the GTK2 theme, have the applied accent color.

**Screenshots**
![image](https://github.com/catppuccin/gtk/assets/13170204/1ae996ac-976c-45cb-bfd7-d7b897beac9e)
![image](https://github.com/catppuccin/gtk/assets/13170204/8abffafb-dbc1-4b51-9a6b-3fe666d2e25d)
**Additional context**
My main used theme folder is user-located, at `~/.local/share/themes`. `~/.themes` is just a symlink to that folder.

**Comment by sgoudham** [comment]
The minimum GTK version for this theme is `3.20`
