### ISSUE TITLE
gtk 4.0 fix for NixOS users

### ISSUE THREAD

**Issue by arunoruto** [catppuccin/gtk#110]
[This](https://www.reddit.com/r/NixOS/comments/11q6exh/homemanager_symlink_to_store/) reddit post explains on how to apply the gtk 4.0 fix using `home.file`. It would be nice to extend the example in the README to incorporate this. I will also provide my config file which works for now:
```nix
# theming.nix
{ pkgs, ...}:
let
  catppuccin_name = "Catppuccin-Macchiato-Standard-Green-Dark";
  catppuccin = pkgs.catppuccin-gtk.override {
        accents = [ "green" ];
        size = "standard";
        tweaks = [ "normal" ];
        variant = "macchiato";
  };
in
{
  # gtk settings
  gtk = {
    enable = true;
    theme = {
      name = catppuccin_name;
      package = catppuccin;
    };
    cursorTheme = {
      name = "Catppuccin-Macchiato-Dark-Cursors";
      package = pkgs.catppuccin-cursors.macchiatoDark;
    };
  };

  home.file.".config/gtk-4.0/gtk.css".source = "${catppuccin}/share/themes/${catppuccin_name}/gtk-4.0/gtk.css";
  home.file.".config/gtk-4.0/gtk-dark.css".source = "${catppuccin}/share/themes/${catppuccin_name}/gtk-4.0/gtk-dark.css";

  home.file.".config/gtk-4.0/assets" = {
    recursive = true;
    source = "${catppuccin}/share/themes/${catppuccin_name}/gtk-4.0/assets";
  };
}
```
I import the `theming.nix` file in my `home.nix` with:
```nix
{ ... }:
{
  imports = [
    ./theming.nix
    ...
  ];
 ...
}
```

**Comment by willswats** [comment]
Here is another way to set the GTK4 theme with Home Manager (must be the same name as the theme set with `gtk.theme.name`):

```nix
 home.sessionVariables.GTK_THEME = "Catppuccin-Mocha-Standard-Blue-dark";
```

**Comment by eclairevoyant** [comment]
You don't need to do all this, you just have the theme name incorrect. Lowercase d for dark.

**Comment by vinicius507** [comment]
> ```nix
>   home.file.".config/gtk-4.0/gtk.css".source = "${catppuccin}/share/themes/${catppuccin_name}/gtk-4.0/gtk.css";
>   home.file.".config/gtk-4.0/gtk-dark.css".source = "${catppuccin}/share/themes/${catppuccin_name}/gtk-4.0/gtk-dark.css";
> 
>   home.file.".config/gtk-4.0/assets" = {
>     recursive = true;
>     source = "${catppuccin}/share/themes/${catppuccin_name}/gtk-4.0/assets";
>   };
> ```

So are the `home.file` bits unneeded?

**Comment by eclairevoyant** [comment]
@vinicius507 correct. but the name keeps changing, you'll have to check whether it's upper or lower case in your version of the package.
