### ISSUE TITLE
Apply theme to self built gtk app

### ISSUE THREAD

**Issue by abhishekmj303** [catppuccin/gtk#111]
I was building a gtk4 app using python, but I am not sure how to get this custom theme applied to it.

I have installed the theme through AUR and it works fine for all the gtk apps installed in the system. Does it require any extra code to apply the global system theme into my app?

PS: The qt apps work fine without doing anything extra.

**Comment by nullishamy** [comment]
GTK themes are handled by the end users of your app, not by applications, pretty sure. You might be able to use some css to theme your own app, but that is not the goal of this port. You should seek guidance from a relevant GTK support avenue if youare still having issues.
