### ISSUE TITLE
Archive Manager (file-roller) falls back to Adwaita

### ISSUE THREAD

**Issue by Lassebq** [catppuccin/gtk#112]
**Describe the bug**
file-roller does not apply Catppuccin GTK theme and uses Adwaita

**Mention your distribution and your theme version**
Arch Linux
Theme version: 0.6.1-2

**Select how you installed the theme**
AUR package 

**Symlinked the gtk-4.0 folder?**
No.

**Expected behavior**
Theme gets applied like with the rest of GTK themes

**Screenshots**
Here's colloid theme, which is unaffected by this issue
![image](https://github.com/catppuccin/gtk/assets/68742864/26b8b674-f6f2-4dd5-8d5e-cfb1cae4c9f0)
And here's catppuccin:
![image](https://github.com/catppuccin/gtk/assets/68742864/af276769-f586-4d7d-9ed0-37f20532741f)

**Additional context**
GTK4 applications use dconf's property (Also, I'm using libadwaita-without-adwaita, which removes a need for symlinking gtk-4.0 folder)

**Comment by sgoudham** [comment]
Hi 👋

Could you please confirm if this issue still exists in our latest release [v0.7.5 (release)](https://github.com/catppuccin/gtk/releases/tag/v0.7.5) ?

Thanks!

**Comment by nullishamy** [comment]
![image](https://github.com/catppuccin/gtk/assets/99221043/1ab7dae3-76f4-4d94-b5c3-995d592af2ef)
Cannot repro. Tested on `v1.0.0-rc3`.

**Comment by Lassebq** [comment]
Haven't encountered it for quite a while now. Closing issue.
