### ISSUE TITLE
not working on pop os apps

### ISSUE THREAD

**Issue by junedgit** [catppuccin/gtk#114]
**Describe the bug**
Theme not working on pop os Application even after linking to gtk4 and trying fixes 

**Mention your distribution and your theme version**
Pop os , mocha-standard-teal-dark, downloaded from github releses.

**Select how you installed the theme**
- GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?** yes
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**

**Screenshots**

**Comment by jh-devv** [comment]
Have you set the `GTK_THEME` environment variable?
