### ISSUE TITLE
Can't get light and dark styles to work with Latte and Mocha themes

### ISSUE THREAD

**Issue by Araly** [catppuccin/gtk#115]
**Describe the bug**
I'm trying to get the Catppuccin themes to work with Gnome's "light" and "dark" styles.
I linked the required files in `~/.config/gtk-4.0` this way:
```
 ls -l ~/.config/gtk-4.0/
total 12
lrwxrwxrwx 1 araly araly 68  8 jul 14.20 assets -> /usr/share/themes/Catppuccin-Mocha-Standard-Teal-dark/gtk-4.0/assets/
lrwxrwxrwx 1 araly araly 69 15 aug 21.34 gtk.css -> /usr/share/themes/Catppuccin-Mocha-Standard-Teal-dark/gtk-4.0/gtk.css
lrwxrwxrwx 1 araly araly 74 15 aug 21.27 gtk-dark.css -> /usr/share/themes/Catppuccin-Mocha-Standard-Teal-dark/gtk-4.0/gtk-dark.css
```
No matter the style selected, light or dark, I can only see apps themed by the Latte theme.
I also tried to have everything point to the Mocha files, and then, no matter the style selected, light or dark, I can only see apps themed by the Mocha theme.

**Mention your distribution and your theme version**
Arch Linux
aur/catppuccin-gtk-theme-mocha 0.6.1-2

**Select how you installed the theme**
- [ ] GitHub Releases
- [x] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
yes

**Expected behavior**
When gnome switches styles from "light" to "dark", the Latte theme is used for the light style, and the Mocha theme is used for the dark style, allowing to change between light and dark colors by pressing a button.

**Screenshots**
in this screenshot, the gtk.css file points to the Mocha theme, and the theming is always Mocha, no matter what style is currently selected. The same happens when gtk.css points to the Latte theme, the theming becomes always Latte.
![Screenshot from 2023-08-15 21-47-56](https://github.com/catppuccin/gtk/assets/24990801/fad916c9-b83a-414f-9087-77c6f43da2b2)
![Screenshot from 2023-08-15 21-48-03](https://github.com/catppuccin/gtk/assets/24990801/5a93998c-476b-4c3d-b5b7-cf1705e23a27)

You can also see that the tweaks apps gets styled correctly, but doesn't follow the catppuccin theming.

**Additional context**
How the theming is supposed to switch between styles I could not find documentation on, so I inferred from what's in the README and what I found in relevant issues. Let me know if I'm way off base, and the behaviour here is expected, and I'm just doing it wrong.

**Comment by isabelroses** [comment]
Some people found that copying the files rather than symlinking them fixed this issue.

**Comment by Araly** [comment]
> Some people found that copying the files rather than symlinking them fixed this issue.

tried to copy the files instead of linking them, in ~/.config/gtk-4.0, but saw no change in behaviour

**Comment by ghostx31** [comment]
As per my knowledge, this does not seem to work this way. 

You can probably look at [Night Theme Switcher](https://gitlab.com/rmnvgr/nightthemeswitcher-gnome-shell-extension) extension and set the files to copy when switching, but this will probably not be seamless for some apps and might require you to restart the session or restart the apps to make them switch.
