### ISSUE TITLE
Some text is black on catpucin mocha

### ISSUE THREAD

**Issue by TadoTheMiner** [catppuccin/gtk#116]
**Describe the bug**
I dont know if it occurs on machiato frape or latte, but on both peach and lavender mocha some text as shown in screenshots is black making it hardly readable

**Mention your distribution and your theme version**
Arch linux, mocha peach +lavender
**Select how you installed the theme**
- [ ] GitHub Releases
- [x] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak
**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**
No because it simply could be done byseting the gtk theme environment variable.
**Expected behavior**
Simply make it white so its light text on dark background not dark text on dark background
**Screenshots**
![Screenshot from 2023-08-16 08-04-00](https://github.com/catppuccin/gtk/assets/100917739/3a30d448-473d-4bef-ab37-f3693b6c933d)
![Screenshot from 2023-08-16 08-03-07](https://github.com/catppuccin/gtk/assets/100917739/40ffd94c-3765-462a-bb52-27900702f044)

**Additional context**
I dont know what to change sdince i never made a gtk theme

**Comment by ghostx31** [comment]
The theme on which the Catppuccin GTK theme is based on, Colloid does not support being used as a theme for GDM. Since you set it as the GDM, stuff is probably broken system-wide.

**Comment by TadoTheMiner** [comment]
It occurs not only in gdm but also on like nautilus and similar places

**Comment by ghostx31** [comment]
Yeah that happens system-wide if you theme GDM with an incompatible theme.

**Comment by TadoTheMiner** [comment]
It occurs even if i use the default gdm theme
