### ISSUE TITLE
GTK4 arch linux.

### ISSUE THREAD

**Issue by Taitep** [catppuccin/gtk#118]
**Describe the bug**
Not really a bug, but when you install via AUR a `~/.themes/` folder does not exist, so i cannot create the symlinks. `${THEME_DIR}` is not defined either, so i do not know how to do this.

**Mention your distribution and your theme version**
Manjaro WSL2 (https://github.com/sileshn/ManjaroWSL2)

**Symlinked the gtk-4.0 folder?**
The issue is that i do not know how...

**Comment by ghostx31** [comment]
The AUR package does not touch the user's home directory so it does not write or create anything inside `~/.themes`. It installs the theme folders inside `/usr/share/themes`.

**Comment by Taitep** [comment]
Thanks!!
