### ISSUE TITLE
Gnome 45 visual bug on updated GUI's

### ISSUE THREAD

**Issue by MuXodious** [catppuccin/gtk#119]
**Describe the bug**
Recent visual update to certain applications (i.e. Gnome Settings and Nautilus) on Gnome 45 borked the theme where the updated portions of the application GUI appears to be alot lighter than the rest of the GUI when the theme is applied.  It appears that some legacy theme is applied. And, changing the dark mode toggle on Gnome Settings doesn't result in any change. 

Top bar's new Workspace indicator thingy isn't quite visually distinctive on white themes (Latte).*

**Mention your distribution and your theme version**
Fedora 39 Beta / Gnome 45.rc / Latest git.

**Select how you installed the theme**
- [ ] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [X] Using the python install script  "install.py frappe -a mauve"
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Yes.

**Expected behavior**
White portions in the screenshots to be the same or similar in tone to the rest of the GUI.

**Screenshots**

![image](https://github.com/catppuccin/gtk/assets/64381665/eeff35d5-c283-4c9f-82e8-0957a979a313)
![image](https://github.com/catppuccin/gtk/assets/64381665/339bf6ab-c218-421c-a3bb-f8dafefbaf33)

For refrence this is how  it looks with "Lattle Mauve":
![image](https://github.com/catppuccin/gtk/assets/64381665/2b2a3c8c-2b47-4abf-81cc-6b5faf16173e)
![image](https://github.com/catppuccin/gtk/assets/64381665/138739a1-34da-4d20-9784-1b693cf737f6)

Topbar Workspace Indicator:
![image](https://github.com/catppuccin/gtk/assets/64381665/1e4fe710-d077-4696-bc57-cd69a3b42e93)
![image](https://github.com/catppuccin/gtk/assets/64381665/8123a77a-c133-4859-bd26-1a38c8788552)

Topbar with Frappe Mauve:
![image](https://github.com/catppuccin/gtk/assets/64381665/8e11b7c6-1484-4e78-a180-5fc0f2a34e0f)
![image](https://github.com/catppuccin/gtk/assets/64381665/ee0a1acb-0cf3-415e-8acd-86562c5afba7)

**Additional context**
Gnome happened, again.

**Comment by ghostx31** [comment]
I have no idea if Colloid upstream has added fixes for Gnome 45 yet, I'll have to keep an eye out on it.

**Comment by JakeMartinezz** [comment]
any fixes? i ran into the same problem

**Comment by ghostx31** [comment]
Should be fixed with the latest release.
