### ISSUE TITLE
Some text editor apps don't look right. Some sections aren't themed.

### ISSUE THREAD

**Issue by 103sbavert** [catppuccin/gtk#123]
**Describe the bug**
Some parts of Gnome Builder and Commit (both Gnome Circles apps) don't look right with the theme.

**Mention your distribution and your theme version**
Catppuccin GTK 0.7.0
Arch Linux
Gnome 44.5

**Select how you installed the theme**
- [ ] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [x] Using the python install script ``python install.py mocha --accent lavender --size standard --tweaks 'rimless' 'normal' -l``
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**
Yes

**Expected behavior**
I expect the right section to be the same or similar color as the rest of the text editor

**Screenshots**
![image](https://github.com/catppuccin/gtk/assets/65838896/7ffbe65b-e850-40fb-8859-70b629858c7a)

**Additional context**
Happens with Gnome Builder as well but I don't have it installed. If need be, I can install it again. Other GTK apps work fine.

**Comment by nullishamy** [comment]
Please retest with the latest release and report back (https://github.com/catppuccin/gtk/releases/tag/v0.7.5).

**Comment by nullishamy** [comment]
![image](https://github.com/catppuccin/gtk/assets/99221043/5e28dd50-24c5-4bf6-a05b-b4ab185b4942)
The only version of Builder I could get to run did not present the issue (though it was not themed at all, maybe because I had to run through a flatpak?) Builder seems practically unused at this point in time though, so I'm unsure if we want to spend time working on support for it as an application.

**Comment by 103sbavert** [comment]
I don't use this theme anymore, I use vanilla gnome now but thanks a lot gor paying attention to this problem. Keep up the good work, cheers!
