### ISSUE TITLE
(Feature Request) Setting To Install All Possible Tweaks?

### ISSUE THREAD

**Issue by n128-98** [catppuccin/gtk#124]
Id like a setting that enables all possible tweaks, such as rimless or normal, to be installed as seperate themes so i can experiment with the tweaks and themes i enjoy.

**Comment by n128-98** [comment]
Like 
Catppuccin-Frappe-Teal-Light-Rimless
Catppuccin-Frappe-Teal-Light-Normal
Catppuccin-Frappe-Teal-Light-Float
Catppuccin-Frappe-Teal-Dark-Black

**Comment by n128-98** [comment]
The Closest Ive Got To This Is A Chain Command That Includes All The Tweaks As Single Themes But Doesnt Inlude Combinations Because I Feel That Would Be Excessive

**Comment by npv12** [comment]
@n128-98 do you basically want all tweaks, colors, and flavours?

**Comment by n128-98** [comment]
yes, that is exactly what i wish

**Comment by rubyowo** [comment]
You can, either:
- Download all the zips from Github Releases
- Use the script like so:
	- `python ./install.py all -a all -d ./dist`
