### ISSUE TITLE
Weird transparent dialog window

### ISSUE THREAD

**Issue by jh-devv** [catppuccin/gtk#128]
Hey!
I love your work but I have been having this issue!
These "dialog" boxes, they seem to be transparent?

I use Nixos 23.05 and the theme's version is 0.4.1

I have installed the theme via:
- [ ] GitHub Releases
- [ ] AUR package 
- [x] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

As expected, it should not look transparent

Here is an picture of the problem, mind me if its bad :3
![20231020_20h34m13s_grim](https://github.com/catppuccin/gtk/assets/122896463/88639320-833b-41e7-9e4c-ea44d7e6f6d9)

**Comment by ghostx31** [comment]
This seems like a compositor issue. What WM are you using and what compositor?

**Comment by jh-devv** [comment]
> This seems like a compositor issue. What WM are you using and what compositor?

Hyprland

**Comment by nekowinston** [comment]
I'm using nixos + catppuccin-gtk + swayfx, I don't have that issue on my end. Does changing window transparency fix the issue for you?

**Comment by jh-devv** [comment]
How would I do that?

**Comment by nekowinston** [comment]
I don't know how you would do that on hyprland, but do you have any window rules that set opacity for floating windows? 🤔
https://wiki.hyprland.org/Configuring/Window-Rules/#window-rules-v2

**Comment by jh-devv** [comment]
> I don't know how you would do that on hyprland, but do you have any window rules that set opacity for floating windows? 🤔
> https://wiki.hyprland.org/Configuring/Window-Rules/#window-rules-v2

I could try! (I'll post the results tomorrow)

**Comment by jh-devv** [comment]
This seem to just do nothing
`windowrulev2 = opacity 1, class:(code))`, I can even set it to `windowrulev2 = opacity 0.1, class:(code)` and it changes the opacity of the popup to basically hide it

**This does not happen with other themes (e.g. Tokyo Night, Gruvbox, Rosé Pine and Adwaita)**. It could be some weird thing with this theme and just appears when using Hyprland + NixOS

@nekowinston @ghostx31

**Comment by ghostx31** [comment]
Can you try to reproduce this with the Colloid theme? If you can reproduce it, it's an upstream issue with Colloid and we could track this issue there.

**Comment by jh-devv** [comment]
> Can you try to reproduce this with the Colloid theme? If you can reproduce it, it's an upstream issue with Colloid and we could track this issue there.

Yea, I can!

**Comment by ghostx31** [comment]
Catppuccin is based on Colloid. That's why I asked you to try reproducing the issue with Colloid now. That would help us pin point the problem.

**Comment by jh-devv** [comment]
> Catppuccin is based on Colloid. That's why I asked you to try reproducing the issue with Colloid now. That would help us pin point the problem.

Ah ok! :3

**Comment by jh-devv** [comment]
Marked as duplicate of https://github.com/vinceliuice/Colloid-gtk-theme/issues/109
