### ISSUE TITLE
GTK4 Support

### ISSUE THREAD

**Issue by Farhaduneci** [catppuccin/gtk#13]
Hey there,

Thank you for this great theme, Is this possible to support GTK4?! Gnome 42 doesn't fully match this theme, Some apps like settings roll back to the default.

![Screenshot from 2022-04-10 13-20-31](https://user-images.githubusercontent.com/53964770/162610431-c204eac2-9552-48fe-b335-679c33e319df.png)

**Comment by Farhaduneci** [comment]
Worked well.

**Comment by AnAlligatorPear** [comment]
Worked for me too!

**Comment by LeonardoLuperini** [comment]
> It's because of libadwaita which doesn't do themes like we're used to. Copy the gtk-4.0/gtk.css file from the theme to ~/.config/gtk-4.0/gtk.css and you'll be set to go:
> 
> ![Skärmbild från 2022-04-12 16-15-18](https://user-images.githubusercontent.com/50339757/162982645-ac063cc7-68e6-4748-a605-3a397bcd801e.png)

Don't work for me 😢 
Any suggestions?

**Comment by sadrach-cl** [comment]
A new version will be released in a few days. I will close this ticket, since I only focus on the new version and I hope it will solve your problem. If not, please create a new support ticket.

Regards.
