### ISSUE TITLE
Wierd text alignment on gnome 45

### ISSUE THREAD

**Issue by n6v26r** [catppuccin/gtk#131]
Text of some UI elements is not centered correctly on gnome 45.

Distro: Manjaro

**Select how you installed the theme**
- [ ] GitHub Releases
- [X] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**

**Expected behavior**
Expected the text to be aligned just like before.

**Screenshots**
This is what I mean:
![Screenshot from 2023-11-07 17-13-52](https://github.com/catppuccin/gtk/assets/108262765/b3b2b0bc-1180-4871-b5c1-0c2b3216d9b6)

**Additional context**
Please mention any additional context that might be applicable.

**Comment by 42Willow** [comment]
Same here, the padding is scuffed.

**Comment by n6v26r** [comment]
Could this be a colloid issue? The latest catppuccin release was a month ago and colloid received a few commits since.
