### ISSUE TITLE
Duplicate Window buttons when viewing night light settings in GNOME settings

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [catppuccin/gtk#134]
![image](https://github.com/catppuccin/gtk/assets/74187631/d1fd4541-a70c-4605-904f-bf2690f148c3)

GNOME ver: 44

LMAO

**Comment by nullishamy** [comment]
Please retest with our latest release (https://github.com/catppuccin/gtk/releases/tag/v0.7.5) and open another issue if this problem persists.
