### ISSUE TITLE
System clock menu's calendar issue

### ISSUE THREAD

**Issue by Eageye101** [catppuccin/gtk#137]
OS used :- Arch Linux 
kernel:- LTS Kernel 

issue:- calander inside gnome clock menu has an offset position 
images 
![Screenshot from 2023-11-19 12-52-42](https://github.com/catppuccin/gtk/assets/107269223/4370ee8d-e753-49b1-951d-00700ed707bb)

**Comment by rubyowo** [comment]
This is most likely an issue with the base theme we use, [colloid-gtk](https://github.com/vinceliuice/Colloid-gtk-theme)
try using that first, and if the issue persists, make an issue in that repo.

**Comment by Eageye101** [comment]
> This is most likely an issue with the base theme we use, [colloid-gtk](https://github.com/vinceliuice/Colloid-gtk-theme) try using that first, and if the issue persists, make an issue in that repo.

well persists with colloid as well but i never noticed it before i guess after the recent update from the aur the issue came to light but nevertheless i will raise an issue in colloid
