### ISSUE TITLE
Nautilus has 2px border around it

### ISSUE THREAD

**Issue by SolsticeSpectrum** [catppuccin/gtk#139]
**Describe the bug**
Nautilus has 2px border around it for some reason even tho no other app has it

**Mention your distribution and your theme version**
Arch Linux

**Select how you installed the theme**
- [ ] GitHub Releases
- [x] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Yes

**Expected behavior**
Nautilus should not have this border

**Screenshots**
![image](https://github.com/catppuccin/gtk/assets/38611351/9670b0bd-21a7-4e2a-ac70-134431cfd02f)

**Additional context**
I used Graphite theme before and it's `install.sh` script had `--tweaks rimless` option which removed this border in Nautilus so maybe study how that works here? https://github.com/vinceliuice/Graphite-gtk-theme

**Comment by DarkReaper231** [comment]
Actually the Colloid theme has this `rimless` tweak as well

**Comment by Yonnji** [comment]
You can play around with "window.solid-csd" selector in the gtk-4.0/gtk.css file (or gtk-dark.css for the dark version).

```
window.solid-csd {
  padding: 0;  /* removes the padding */
  border: none;  /* removes the border */
  box-shadow: none;  /* removes the double border */
}
```

I wouldn't recommend removing everything because you will not be able to resize the window without any borders, but you can try each option and check how it works for you.

**Comment by DarkReaper231** [comment]
@Yonnji Omg thank you so much! This did help!

**Comment by nullishamy** [comment]
This should be reported upstream, and ideally PRd into upstream if there is indeed a bug. Doesn't seem like a downstream issue.
