### ISSUE TITLE
Build dependency on git repository

### ISSUE THREAD

**Issue by braheezy** [catppuccin/gtk#14]
Hello. I obtained the source code via tarball and tried building the asset packages with a `make package` and yep, it threw errors because I wasn't using a `git clone` of the project. 

I was able to fix it with a couple tweaks to the `Makefile` and `install.sh`. 

I'm wondering if there was a particular reason `git` commands are used to determine the working directory. Would you be interested in a pull request with an alternative method?

**Comment by sadrach-cl** [comment]
A new version will be released in a few days. I will close this ticket, since I only focus on the new version and I hope it will solve your problem. If not, please create a new support ticket.

Regards.
