### ISSUE TITLE
Mocha not working on NixOS, theme v0.7.1

### ISSUE THREAD

**Issue by Nintron27** [catppuccin/gtk#140]
**Describe the bug**
Trying to use Mocha with home manager on NixOS don't work. Other variations work fine, but Mocha, specifically Catppuccin-Mocha-Standard-Mauve-Dark, just shows the default GTK theme.

**Mention your distribution and your theme version**
NixOS 23.11, theme version 0.7.1 (I'm using unstable in the home manager.

**Select how you installed the theme**
- [ ] GitHub Releases
- [ ] AUR package 
- [x] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
No

**Expected behavior**
The Catppuccin-Mocha-Standard-Mauve-Dark to display. Instead, I just get the default theme as if there is no "Catppuccin-Mocha-Standard-Mauve-Dark".

**Screenshots**
N/A

**Additional context**
If I switch back to version 0.7.0 it works fine. Thus, I am using the 23.11 release instead of unstable for now.

**Comment by rubyowo** [comment]
do you still have this issue?

**Comment by Nintron27** [comment]
Sorry I missed the initial comment. This has been fixed now. I don't know exactly what update fixed it but I'm on 23.11 still and it is working.
