### ISSUE TITLE
Buttons problem

### ISSUE THREAD

**Issue by Lianaja32** [catppuccin/gtk#142]
**Describe the bug**
The close, minimize and maximize buttons are not suppose to look like in the screenshot below. 

**Mention your distribution and your theme version**
I'm using Ubuntu Unity 23.10 (Kernel 6.5.0-14-generic) and the theme's version is 0.7.1.

**Select how you installed the theme**
- [x] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
No, because it's not available.

**Expected behavior**
It's suppose to be like in Gnome (here with Flatseal).

**Screenshots**
 
![Capture d’écran du 2024-01-05 09-28-25](https://github.com/catppuccin/gtk/assets/79010647/9c7b695c-778c-4de1-8530-9ae5a169075e)

![Capture d’écran du 2024-01-05 22-48-43](https://github.com/catppuccin/gtk/assets/79010647/f367ae41-1a9f-4f94-8168-132da1fbff04)

**Additional context**
When hovering the global menu, I find the buttons weird.

**Comment by nullishamy** [comment]
Please open a new issue if this is still present in the latest release (https://github.com/catppuccin/gtk/releases/tag/v0.7.5).
