### ISSUE TITLE
GTK4 install instructions are incorrect

### ISSUE THREAD

**Issue by CallMeEchoCodes** [catppuccin/gtk#143]
**Describe the bug**

**Mention your distribution and your theme version**
Artix linux (archlinux fork)
catppuccin-gtk-theme-mocha `0.7.1-1`

**Select how you installed the theme**
- [ ] GitHub Releases
- [x] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**
Yes I did! This is the issue. The instructions say to use a few symlinks that just don't work and just create invalid symlinks (this occurs even after changing the environment variables to full paths). I found that running `ln -sf /usr/share/themes/Catppuccin-Mocha-Standard-Pink-Dark/gtk-4.0 $HOME/.config/gtk-4.0` worked and themed everything instantly. From what i can see, the theme was reorganised at some point and that broke stuff. 

**Expected behavior**
I expected the `README.md` to contain accurate information and theme my GTK4 apps

**Comment by Sewer56** [comment]
Thanks for this report. This helped me too. 

As I've never themed GTK4 before, and I don't know any convenient GUI to do so, this helped me figure this out, as the current wording in the README confused me.

**Comment by SpomJ** [comment]
I believe install instructions assume you do something like `export THEME_DIR=~/.icons/Catppuccin-Mocha-Standard-Blue-Dark` beforehand, in which case it does, indeed work. The reason it creates invalid symlinks for you is that $THEME_DIR is not set, therefore it's substituted for empty string, unwrapping to "/gtk-4.0/gtk.css", which is indeed valid syntax, but invalid location.

Probably should mention something about setting $THEME_DIR in readme.

**Comment by SpomJ** [comment]
Also why did you check the AUR, but not the releases box

**Comment by nullishamy** [comment]
This has been fixed with the new build system (links for you), and in the new README (accurately describes the variable requirement)
