### ISSUE TITLE
xfwm4 are broken

### ISSUE THREAD

**Issue by lime-desu** [catppuccin/gtk#144]
**Describe the bug**
Title

**Mention your distribution and your theme version**
```
❯  lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux trixie/sid
Release:	n/a
Codename:	trixie
```

**Select how you installed the theme**
- [x] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [ ] Flatpak
- [ ] Using the python install script 

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**

- Nope don't have gtk4 applications used

**Expected behavior**

- Should use the catppuccin colorcheme instead of colloid

**Screenshots**

| Latest Version (0.7.1) | Older Version (0.3 below) |
|:----------------------:|:-------------------------:|
| ![broken_using_latest_version](https://github.com/catppuccin/gtk/assets/114978689/3749852f-02c4-43e7-957d-de77fef3c518) | ![working_using_older_version](https://github.com/catppuccin/gtk/assets/114978689/2782847e-1f4a-41d7-ba2f-4ef2751027ca) |

**Additional context**

- The working version afaik is v0.3 something, and version above that till latest are broken

**Comment by vmaerten** [comment]
I've the same issue

**Comment by vmaerten** [comment]
@lime-desu I've managed to get it work by compiling manually as explained here : https://github.com/catppuccin/gtk/issues/77#issuecomment-1575480232

**Comment by rubyowo** [comment]
There should not be any difference between compiling manually and the github release.
We install inkscape and compile it with --recreate-assets [(Source)](https://github.com/catppuccin/gtk/blob/main/.github/workflows/release.yml#L24-L26)

**Comment by nullishamy** [comment]
Please retest with our latest release, v1.0.0-rc3 (https://github.com/catppuccin/gtk/releases/tag/v1.0.0-rc3). There should be no outstanding issue with xfwm4 now!
