### ISSUE TITLE
Theme parse error "gtkmix"

### ISSUE THREAD

**Issue by tobias-haenel** [catppuccin/gtk#145]
**Describe the bug**
I get theme parser errors within the following css files and GTK 4:

```
Gtk-WARNING **: 17:33:15.315: Theme parser error: gtk.css:7791:21-28: Expected a valid color.
Gtk-WARNING **: 17:33:15.316: Theme parser error: gtk.css:7796:21-28: Expected a valid color.
Gtk-WARNING **: 17:33:15.316: Theme parser error: gtk.css:7814:21-28: Expected a valid color.
Gtk-WARNING **: 17:33:15.316: Theme parser error: gtk.css:7820:21-28: Expected a valid color.
Gtk-WARNING **: 17:33:15.332: Theme parser error: gtk-dark.css:7791:21-28: Expected a valid color.
Gtk-WARNING **: 17:33:15.332: Theme parser error: gtk-dark.css:7796:21-28: Expected a valid color.
Gtk-WARNING **: 17:33:15.332: Theme parser error: gtk-dark.css:7814:21-28: Expected a valid color.
Gtk-WARNING **: 17:33:15.332: Theme parser error: gtk-dark.css:7820:21-28: Expected a valid color.
```

The respective colors use the gtkmix function, e.g.
```css
.sidebar-pane banner > revealer > widget {
  background-color: gtkmix(#74c7ec, #11111b, 30%);
  color: #FFFFFF;
}
```
**Mention your distribution and your theme version**
ArchLinux, catppuccin-gtk-theme-mocha v0.7.1

**Select how you installed the theme**
- [ ] GitHub Releases
- [x] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? 
yes

**Expected behavior**
No warnings

**Screenshots**
![image](https://github.com/catppuccin/gtk/assets/6195791/6de73523-5b2c-4639-9200-0ed23a335b04)

**Additional context**
Please mention any additional context that might be applicable.

**Comment by tobias-haenel** [comment]
@vinceliuice Might be related to a missing definition of the gtkmix function in Colloid https://github.com/vinceliuice/Colloid-gtk-theme/blob/8e4f478913fef8cb6437cabef1992ad04ad84a2f/src/sass/_colors.scss#L1
Orchis added a fix  for this https://github.com/vinceliuice/Orchis-theme/commit/b27b36861c63a1d54ac9617b7f10ce35cfd46419

**Comment by joezhouchenye** [comment]
@tobias-haenel Thanks. Although I am not using catppuccin, this solved my problem with another theme.

**Comment by Lassebq** [comment]
I'm surprised no one bothered to report it upstream

**Comment by Lassebq** [comment]
It's fixed now

**Comment by sgoudham** [comment]
This should be fixed now via https://github.com/catppuccin/gtk/releases/tag/v0.7.4, feel free to reopen if it's not.
