### ISSUE TITLE
Pop_OS treating dark theme as light theme and missing theme changes

### ISSUE THREAD

**Issue by nljackson2020** [catppuccin/gtk#147]
**Describe the bug**
Installed mocah themes using the python script, setup symlinks for gtk4, and set the env variable. Themes are working in applications but not the top bar, system drop down menu, launcher (when pressing superkey), and applications tray (background color didn't change but text did).

**Mention your distribution and your theme version**
 Pop!_OS 22.04 LTS x86_64 
Kernel: 6.6.6-76060606-generic 
Theme: Catppuccin-Mocha-Standard-Green-Dark

**Select how you installed the theme**
- [ ] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [x] Using the python install script  python install.py mocha -a all --tweaks rimless -d /usr/share/themes
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**
Yes, created symlinks

**Expected behavior**
Use of mocha green dark theme in top bar, system drop down menus, launcher, applications tray.

**Screenshots**
![image](https://github.com/catppuccin/gtk/assets/11460477/d06b11b3-292d-4b36-8086-3a28d2326c77)
![image](https://github.com/catppuccin/gtk/assets/11460477/95170b18-6bda-44b4-a890-95fb543ebbe7)
![image](https://github.com/catppuccin/gtk/assets/11460477/42b5b0c2-2fbb-4370-837d-9a906642e41e)

**Additional context**
Please mention any additional context that might be applicable.

**Comment by Ernestas-t** [comment]
I'm experiencing the same issue on my laptop. my desktop has the elements themed correctly, but on my laptop majority of the menus are white. the only difference between the 2 computers is my desktop is using nvidia gpu and my laptop is using amd.

**Comment by nljackson2020** [comment]
I'm using a nvidia gpu on my desktop.

**Comment by rubyowo** [comment]
@Ernestas-t are you using PopOS! as well?

**Comment by Ernestas-t** [comment]
@rubyowo indeed i am

**Comment by rubyowo** [comment]
Oh... wait of course you are... oops
anyway, how did you install the theme?

**Comment by Ernestas-t** [comment]
> Oh... wait of course you are... oops
> 
> anyway, how did you install the theme?

On both pc's its the same. From the release zip. Both are using the same catppuccin macchiato theme

**Comment by rubyowo** [comment]
Also, need to comment on this so it doesn't get buried:

there is a fundamental flaw with our light/dark themes, ideally latte wouldn't exist as a standalone theme and rather as a light mode in all of the other dark flavors.

Also @sgoudham on PopOS! says that he doesn't notice any issues with dark/light stuff

**Comment by michaeldebetaz** [comment]
Same for me on Pop OS with the mocha flavour. So far the only problem is with the quick search menu which presents in light mode but highlight in dark mode, making the highlighted text unreadable.
![Screenshot from 2024-02-29 13-45-53](https://github.com/catppuccin/gtk/assets/69384439/6db6cd76-a1be-43a2-b9ea-7f176ee2d291)

**Comment by Limosk** [comment]
Had the same issue, managed to fix it by installing https://extensions.gnome.org/extension/19/user-themes/ and changing the shell settings to this theme.

**Comment by michaeldebetaz** [comment]
> Had the same issue, managed to fix it by installing https://extensions.gnome.org/extension/19/user-themes/ and changing the shell settings to this theme.

Thank you very much for the tip! It worked :)
