### ISSUE TITLE
Sidebar in certain apps is not themed

### ISSUE THREAD

**Issue by slumberling** [catppuccin/gtk#148]
**Describe the bug**
Sidebar in certain apps (Files, Settings) is not themed

**Mention your distribution and your theme version**
Nobara 39 / GNOME 45.3 / git latest

**Select how you installed the theme**
- [ ] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [x] Using the python install script `python install.py mocha -a lavender --link`
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Yes

**Expected behavior**
All UI elements are themed correctly

**Screenshots**
![Screenshot from 2024-02-04 18-05-23](https://github.com/catppuccin/gtk/assets/7861146/675aef80-7697-4728-9f42-3cae625b653d)
![Screenshot from 2024-02-04 18-05-51](https://github.com/catppuccin/gtk/assets/7861146/50f642b6-72f8-4825-af24-e8fdd5e33ce1)

**Comment by fivelfox** [comment]
having the exact same issue on Fedora 39 Workstation with beta flatpak-beta Gradience

**Comment by rubyowo** [comment]
Can you confirm this issue happens on Colloid GTK?

**Comment by Araly** [comment]
is there a way we can test that ? is colloid some other project that we should install and test ?

**Comment by slumberling** [comment]
> Can you confirm this issue happens on Colloid GTK?

It does not.

Colloid-Purple-Dark-Dracula installed with command `./install.sh -t purple -c dark -l --tweaks dracula`

Looks.. as expected.

![Screenshot from 2024-03-29 20-18-40](https://github.com/catppuccin/gtk/assets/7861146/92e6c08a-2355-4d3c-93be-5bd2ccde91dd)

**Comment by rubyowo** [comment]
i see

**Comment by mainrs** [comment]
Happens on my system too. I use the mauve light theme installed via AUR and symlinked the GTK4 folder. However, there is some other stuff that is wrong too. Take a look at the "address bar" of nautilus that shows the folder you are in right now. Its text color is white on top of a light background.

![image](https://github.com/catppuccin/gtk/assets/5113257/faa506e2-2664-4f4d-822f-f96d0a9c7aa4)

**Comment by nullishamy** [comment]
Please retest with the colloid update, released as 0.7.5 (https://github.com/catppuccin/gtk/releases/tag/v0.7.5)

**Comment by nullishamy** [comment]
![image](https://github.com/catppuccin/gtk/assets/99221043/f92fe967-9971-4176-94f7-f518a281720a)
Cannot repro on `v1.0.0-rc3`
