### ISSUE TITLE
Support libadwaita's button and entry styles

### ISSUE THREAD

**Issue by TestingPlant** [catppuccin/gtk#15]
Some of the styled widgets in the style classes demo in `adwaita-1-demo` don't have the correct colors.

With the adwaita theme:
![image](https://user-images.githubusercontent.com/44930139/163871529-67a4b231-1b0d-4cee-945b-7eca14644ad9.png)

With catppuccin:
![imagen](https://user-images.githubusercontent.com/44930139/163871688-c8dd14fc-b677-437f-aaa1-a337f0978502.png)

**Comment by TGRush** [comment]
In theory this should only require upstreaming this theme to what the latest base Colloid theme currently provides, as that fully supports LibAdwaita/GTK4

**Comment by sadrach-cl** [comment]
A new version will be released in a few days. I will close this ticket, since I only focus on the new version and I hope it will solve your problem. If not, please create a new support ticket.

Regards.
