### ISSUE TITLE
Some text is black making it unreadable

### ISSUE THREAD

**Issue by TadoTheMiner** [catppuccin/gtk#150]
**Describe the bug**
As mentioned in my previous  issue  #116  some text is black making it unreadable and this occurs even when not using it as gdm theme (or even when not using gdm at all). The text is for example on the bottom right corner of nautilus as shown in the screenshot.
**Mention your distribution and your theme version**
Please mention your Linux distribution and the theme version you've installed.
Arch Linux 0.7.1-1
**Select how you installed the theme**
- [ ] GitHub Releases
- [x] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**
Not needed, i set the gtk theme variable
**Expected behavior**
it being #cdd6f4 or something white
**Screenshots**
If possible, please share screenshots of the bug you've encountered. 
![image](https://github.com/catppuccin/gtk/assets/100917739/73b93acf-293a-45f8-a2e8-774c0fcf77d2)

**Additional context**
Please mention any additional context that might be applicable.

**Comment by StefanYohansson** [comment]
try this section of readme 

https://github.com/catppuccin/gtk#for-gtk-4-users

It works for me after doing this:
```
ln -sf /usr/share/themes/Catppuccin-Macchiato-Standard-Pink-Dark/gtk-4.0/ $HOME/.config/gtk-4.0
```

**Comment by nullishamy** [comment]
![image](https://github.com/catppuccin/gtk/assets/99221043/0c4d2d41-5461-4a8c-8ad5-fe48b35d72dc)
Cannot repro on `v1.0.0-rc3`

**Comment by TadoTheMiner** [comment]
Well yeah symlinking fixed it
