### ISSUE TITLE
Buggy corners in widgets

### ISSUE THREAD

**Issue by weebcyberpunk** [catppuccin/gtk#16]
Hello, first thanks and congratulations for maintaining this awesome theme and I apologize by the issue created in the wrong repository. 

I'm having a minor issue with the corners of GTK apps, which didn't happened with other themes that I tried (no one had rounded corners on widgets). I tried with and without composition, and it keeps like that.

I'm running Arch Linux and I've installed the theme via the AUR package. I'm currently running the DWM window manager with Picom compositor and the default settings. Both gtk-engine-murrine and gnome-themes-extra are installed. 
![image](https://user-images.githubusercontent.com/99452238/167748109-5d0fa6ac-350e-4963-b914-39bc81bc020b.png)

**Comment by sadrach-cl** [comment]
A new version will be released in a few days. I will close this ticket, since I only focus on the new version and I hope it will solve your problem. If not, please create a new support ticket.

Regards.

**Comment by sistematico** [comment]
Same issue here.

Catppuccin-Macchiato-Standard-Blue-dark:
![print](https://github.com/catppuccin/gtk/assets/97509/fb20a3ca-1ca0-4e8d-8a34-9fc70ee06295)

Arc-dark:
![print2](https://github.com/catppuccin/gtk/assets/97509/2d830980-eb4a-4f97-b8c3-77a686c80ea2)
