### ISSUE TITLE
symbols in binary leading to slow install

### ISSUE THREAD

**Issue by TuxMC-sys** [catppuccin/gtk#160]
**Describe the bug**
When installing catppuccin gtk, paru is spending a lot of time on   -> Stripping unneeded symbols from binaries and libraries...

**Mention your distribution and your theme version**
Please mention your Linux distribution and the theme version you've installed.
Arch; all
**Select how you installed the theme**
- [ ] GitHub Releases
- [x] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**
N/A
**Expected behavior**
Not hanging...
**Screenshots**
If possible, please share screenshots of the bug you've encountered. 

**Additional context**
Please mention any additional context that might be applicable.
  -> Stripping unneeded symbols from binaries and libraries...

**Comment by rubyowo** [comment]
but all the AUR package does is download the zip files and put them in the correct directory... there *are* no binaries nor libraries to strip from

**Comment by nullishamy** [comment]
As described, there should be no binaries in the release for paru to strip. Maybe try reporting upstream in paru? Doesn't seem like our concern. Closing as not planned.
