### ISSUE TITLE
🚧 Looking For Maintainers 🚧

### ISSUE THREAD

**Issue by ghostx31** [catppuccin/gtk#164]
Hi everyone,

Catppuccin/gtk is currently looking for maintainers. The current maintainers, me, [Syndrizzle](https://github.com/Syndrizzle), [npv12](https://github.com/npv12) and  [ruby](https://github.com/rubyowo) have been busy and haven't had enough time to take care of the repository and keep it updated. 

Issues have been popping up on the repository and none of us currently have the capacity to look into this. So, we hope to find more maintainers for this repository because maintaining this repository is a big undertaking and requires a lot of time and attention.

I'd also like to highlight that we currently use the fantastic [Colloid GTK theme](https://github.com/vinceliuice/Colloid-gtk-theme/) from [Vince](https://github.com/vinceliuice) as the base but since we build on top of the Colloid theme checked out a submodule, its very difficult to deviate from upstream colloid and we are usually dependent on any fixes being made upstream before we can rollout the changes on this repository. We also lose control over how we want certain elements to look in the final theme.

**We hope to move to some other theme as a base or ideally, build catppuccin/gtk from scratch, which we realise is a huge undertaking.**

With these things in mind, we want to put out the notice that while this repository is minimally maintained, we are looking for a maintainer with experience in maintaining and working with a GTK theme.

If you are interested, please leave a comment in this issue, and also join the Discord server for more synchronous communication, if possible.

spooky

**Comment by NathanGavenski** [comment]
Hey,

I don't have much experience maintaining repositories and with GTK, but I'd like to help.

**Comment by andreasgrafen** [comment]
> Experience can only be gained from trying, failing and learning — success will come along the way.

So I wouldn't say that this is a negative thing. From the little experience I personally have with theming GTK it's not super hard to get into and the maintenance part is mostly repetetive work whenever stuff is updated or bugs come up.

While I haven't been involved with this repo specifically I would say that we generally appreciate all sorts of contributions and that people involved are by no means all experts. c:

**Comment by sgoudham** [comment]
We are no longer looking for maintainers. To understand why, see #262
