### ISSUE TITLE
Apps on Dashboard and Dash are unthemed on Gnome 46.

### ISSUE THREAD

**Issue by sancalabs** [catppuccin/gtk#165]
**Describe the bug**
When you enter the Dashboard on Gnome 46, apps on the Dashboard and the Dash look unthemed.

**Mention your distribution and your theme version**
Arch Linux && 0.7.3-1

**Select how you installed the theme**
- [ ] GitHub Releases
- [*] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
No.

**Expected behavior**
I expected the apps to be a pastel catppuccin-like shade of gray, instead of the normal Adwaita dark-gray.

**Screenshots**
![Screenshot from 2024-04-07 21-04-06](https://github.com/catppuccin/gtk/assets/166131614/956afa47-143d-4739-9874-4ff3a96112f5)

![Screenshot from 2024-04-06 10-39-07](https://github.com/catppuccin/gtk/assets/166131614/8d4577da-a978-4f71-a445-792665a05855)

**Comment by fabionebbia** [comment]
Look s like it may have been fixed in upstream Colloid theme
