### ISSUE TITLE
Setting config for GTK-4 Attribute missing

### ISSUE THREAD

**Issue by Schlentzen** [catppuccin/gtk#167]
**Describe the bug**
When i set the config for nix i get the error: 
 `error: attribute 'theme' missing`
at

```
 xdg.configFile = {
    "gtk-4.0/assets".source = "${config.gtk.theme.package}/share/themes/${config.gtk.theme.name}/gtk-4.0/assets";
    "gtk-4.0/gtk.css".source = "${config.gtk.theme.package}/share/themes/${config.gtk.theme.name}/gtk-4.0/gtk.css";
    "gtk-4.0/gtk-dark.css".source = "${config.gtk.theme.package}/share/themes/${config.gtk.theme.name}/gtk-4.0/gtk-dark.css";
  };
```
**Mention your distribution and your theme version**
NixOS 23.11

**Select how you installed the theme**
- [ ] GitHub Releases
- [ ] AUR package 
- [ X] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**
I try

HomeManager is installed as a module like this:

```
 imports =
    [
      # Include the results of the hardware scan.
      ./hardware-configuration.nix
      <home-manager/nixos>
    ];
```
```
home-manager.users.username = {
    home.stateVersion = "23.11";
    imports = [ ./dconf.nix ];
    gtk = {
      enable = true;
      theme = {
        name = "Catppuccin-Macchiato-Compact-Pink-Dark";
        package = pkgs.catppuccin-gtk.override {
          accents = [ "pink" ];
          size = "compact";
          tweaks = [ "rimless" "black" ];
          variant = "macchiato";
        };
      };
    };
    xdg.configFile = {
      "gtk-4.0/assets".source = "${config.gtk.theme.package}/share/themes/${config.gtk.theme.name}/gtk-4.0/assets";
      "gtk-4.0/gtk.css".source = "${config.gtk.theme.package}/share/themes/${config.gtk.theme.name}/gtk-4.0/gtk.css";
      "gtk-4.0/gtk-dark.css".source = "${config.gtk.theme.package}/share/themes/${config.gtk.theme.name}/gtk-4.0/gtk-dark.css";
    };
  };
```

**Comment by Schlentzen** [comment]
Found the error, it had to be:

`home-manager.users.username ={ config, pkgs, ... }:  {`

**Comment by kualta** [comment]
can confirm, this fixes the issue. thanks @Schlentzen! I think this can be closed now.
