### ISSUE TITLE
0.7.3 Latte tabs are too dark

### ISSUE THREAD

**Issue by denisstrizhkin** [catppuccin/gtk#168]
**Describe the bug**
Tabs are too dark? on 0.7.3
![image](https://github.com/catppuccin/gtk/assets/57726946/fd327821-ec10-436b-a8b2-56139f5cbb55)

**Mention your distribution and your theme version**
Gentoo, 0.7.3

**Select how you installed the theme**
- [x] GitHub Releases

**Symlinked the gtk-4.0 folder?**
no

**Expected behavior**
Lighter tabs like on 0.7.2
![image](https://github.com/catppuccin/gtk/assets/57726946/4ba8aec0-381c-4242-b757-9d99589bec27)

**Comment by sgoudham** [comment]
Should be fixed by https://github.com/catppuccin/gtk/releases/tag/v0.7.4
