### ISSUE TITLE
No `grey` asset

### ISSUE THREAD

**Issue by fufexan** [catppuccin/gtk#17]
I'm trying to build the theme with the `-t all` flag, but it fails at building the `grey` theme.
```sh
catppuccin-gtk> Installing '/nix/store/7pa3v3k64k3rkf8qxbs9csi9ns1q5vgr-catppuccin-gtk-0.1.4/share/themes/Catppuccin-grey'...
catppuccin-gtk> cp: cannot stat '/build/source/src/assets/gtk/assets-grey': No such file or directory
```

Is it possible to add it?

**Comment by sadrach-cl** [comment]
A new version will be released in a few days. I will close this ticket, since I only focus on the new version and I hope it will solve your problem. If not, please create a new support ticket.

Regards.
