### ISSUE TITLE
flatpak theme org.gtk.Gtk3theme.Catppuccin-Mocha branch 3.22 is EOL

### ISSUE THREAD

**Issue by etrigan63** [catppuccin/gtk#171]
**Describe the bug**
Info: runtime org.gtk.Gtk3theme.Catppuccin-Mocha branch 3.22 is end-of-life, with reason:
   Themes have been renamed to a new naming scheme.

**Mention your distribution and your theme version**
3.22

**Select how you installed the theme**
- [ ] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [X] Flatpak

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**
NA
**Expected behavior**
flatpak of theme should be updated to the new naming scheme

**Screenshots**
If possible, please share screenshots of the bug you've encountered. 

**Additional context**
Please mention any additional context that might be applicable.

**Comment by ghostx31** [comment]
Hi, 
Can you share how you installed the GTK Theme? We have not published the GTK Theme on Flathub so we have no clue what's the issue here.

**Comment by etrigan63** [comment]
❯ flatpak info org.gtk.Gtk3theme.Catppuccin-Mocha

Catppuccin (Mocha) Gtk Theme - Soothing pastel theme for GTK3 (Mocha)

          ID: org.gtk.Gtk3theme.Catppuccin-Mocha
         Ref: runtime/org.gtk.Gtk3theme.Catppuccin-Mocha/x86_64/3.22
        Arch: x86_64
      Branch: 3.22
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 588.3 kB

      Commit: def1ee10f0358ba479cecaa517e91522b42dfa5dbc8263756f188f21efc12440
      Parent: 6060610e3a83ebc81d1504cd7aa1070644e21a5c71598f461a9b0404467d3c9f
     Subject: EOL (da010941)
        Date: 2022-12-13 09:55:33 +0000
 End-of-life: Themes have been renamed to a new naming scheme.

**Comment by ghostx31** [comment]
I see. These are pretty old and haven't been updated in quite a long time. 
Also, we have not officially published the GTK package on Flatpak and we do not know who maintains them (they seem to be unmaintained). 

This isn't the officially supported method of installation anyway @etrigan63, please install the theme from Github releases or from any other supported installation method. Closing this issue.
