### ISSUE TITLE
A problem about switch buttons 

### ISSUE THREAD

**Issue by LuDreamst** [catppuccin/gtk#179]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe the bug.

As a person whose first language is not English, I am afraid I cannot describe the problem succinctly and accurately. So I upload a video.  

https://github.com/catppuccin/gtk/assets/53106447/63afe9c8-03e2-4c0e-8328-e35203a47cff

### How did you install the theme?

GitHub Release

### If using GTK4, have you symlinked the "gtk-4.0" folder?

- [X] I have symlinked the `gtk-4.0` folder.

### What GNOME version are you seeing the bug on?

GNOME Version 46.1

**Comment by nullishamy** [comment]
Please test with the latest release (https://github.com/catppuccin/gtk/releases/tag/v1.0.0-rc3) and report back!

**Comment by nullishamy** [comment]
Cannot repro:

https://github.com/catppuccin/gtk/assets/99221043/7bf5748b-6e88-4b13-b2be-3bae3a1823b6

**Comment by LuDreamst** [comment]
The lastest releases work well.
Thanks a lot!
