### ISSUE TITLE
No Updates?

### ISSUE THREAD

**Issue by xukashi** [catppuccin/gtk#18]
hi, vinceliuice is constantly updating his theme. Nothing has happened here for 4-5 months. Can we assume that this theme is dead?

**Comment by ludvigng** [comment]
They seem to be updating everything to the catppuccin 2.0 styles, you can follow the progress here: https://github.com/orgs/catppuccin/projects/2

**Comment by sadrach-cl** [comment]
A new version will be released in a few days. I will close this ticket, since I only focus on the new version and I hope it will solve your problem. If not, please create a new support ticket.

Regards.
