### ISSUE TITLE
Recolouring xfwm4

### ISSUE THREAD

**Issue by nullishamy** [catppuccin/gtk#188]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe the issue.

We need to reimplement this, this will involve PNG manipulation, which the upstream & old build system did through the `inkscape` cli.

**Comment by nullishamy** [comment]
We should also fix https://github.com/catppuccin/gtk/issues/144 whilst we implement this.

**Comment by isabelroses** [comment]
was this closed by https://github.com/catppuccin/gtk/pull/206?
