### ISSUE TITLE
[v1.0.0-rc1] Accents are all mauve?

### ISSUE THREAD

**Issue by higherorderfunctor** [catppuccin/gtk#195]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe the bug.

In the latest release it looks like the accent color is always mauve.  Confirmed in both the downloads on the release page and building myself.  They followed the theme in https://github.com/catppuccin/gtk/commit/0c3e8817da94769887c690b2211e006b287b27b1.

https://github.com/catppuccin/gtk/commit/13f2a344c855c2119b5e7e72e8b06bb98053de0f (v1.0.0-rc1)
```sh
$ grep -R 'accent.*#' ~/Downloads/catppuccin-macchiato-sky-standard+default
~/Downloads/catppuccin-macchiato-sky-standard+default/gtk-4.0/gtk-dark.css:@define-color accent_bg_color #c6a0f6;
~/Downloads/catppuccin-macchiato-sky-standard+default/gtk-4.0/gtk-dark.css:@define-color accent_color #c6a0f6;
~/Downloads/catppuccin-macchiato-sky-standard+default/gtk-4.0/gtk.css:@define-color accent_bg_color #c6a0f6;
~/Downloads/catppuccin-macchiato-sky-standard+default/gtk-4.0/gtk.css:@define-color accent_color #c6a0f6;
$ grep -R 'accent.*#' ~/Downloads/catppuccin-mocha-green-standard+default
~/Downloads/catppuccin-mocha-green-standard+default/gtk-4.0/gtk-dark.css:@define-color accent_bg_color #cba6f7;
~/Downloads/catppuccin-mocha-green-standard+default/gtk-4.0/gtk-dark.css:@define-color accent_color #cba6f7;
~/Downloads/catppuccin-mocha-green-standard+default/gtk-4.0/gtk.css:@define-color accent_bg_color #cba6f7;
~/Downloads/catppuccin-mocha-green-standard+default/gtk-4.0/gtk.css:@define-color accent_color #cba6f7;
```

https://github.com/catppuccin/gtk/commit/0c3e8817da94769887c690b2211e006b287b27b1
```sh
$ grep -R 'accent.*#' Catppuccin-Macchiato-Compact-Sky-Dark
Catppuccin-Macchiato-Compact-Sky-Dark/gtk-4.0/gtk.css:@define-color accent_bg_color #91d7e3;
Catppuccin-Macchiato-Compact-Sky-Dark/gtk-4.0/gtk.css:@define-color accent_color #91d7e3;
Catppuccin-Macchiato-Compact-Sky-Dark/gtk-4.0/gtk-dark.css:@define-color accent_bg_color #91d7e3;
Catppuccin-Macchiato-Compact-Sky-Dark/gtk-4.0/gtk-dark.css:@define-color accent_color #91d7e3;
```

### How did you install the theme?

GitHub Release

### If using GTK4, have you symlinked the "gtk-4.0" folder?

- [X] I have symlinked the `gtk-4.0` folder.

### What GNOME version are you seeing the bug on?

N/A

**Comment by sgoudham** [comment]
Thanks for raising, unsure how we missed that 😄 

This should now be fixed in https://github.com/catppuccin/gtk/releases/tag/v1.0.0-rc2 

Feel free to re-open if it's still not working!

**Comment by higherorderfunctor** [comment]
Working for me now also using a custom nix overlay.  Thanks!

**Comment by bobby-welch** [comment]
I am still seeing this issue with the latest release (v1.0.0-rc4).  Thanks.
