### ISSUE TITLE
GDM Theme Support

### ISSUE THREAD

**Issue by braheezy** [catppuccin/gtk#21]
Hello! I was able to customize the GDM login theme!

**Before**:
![GDM_Default](https://user-images.githubusercontent.com/11700503/177062424-71c6da8f-27ab-48c4-8374-4698f73d7d9f.png)

**After**:
![GDM_catppuccin](https://user-images.githubusercontent.com/11700503/177064520-4a7b6a96-68c9-4be1-b509-2f390544c803.png)

As it turns out, GDM just needs the assets from the `gnome-shell` directory. It required a new `*.gresources.xml` file that I had to write plus a "compilation" step to create the binary `.gresources` file that GDM needs. Setting the logo was something extra I had to configure as well.

And I'll mark this as related to catppuccin/catppuccin#101.

**EDIT**: I have instructions to apply the assets to GDM in [one my projects](https://github.com/braheezy/catppuccin-gtk-rpm#usage).

**Comment by pewduckwei** [comment]
Love it

**Comment by LaylaMeower** [comment]
Any updates?

**Comment by npv12** [comment]
> Any updates?

Gdm should be functional with the latest releases if you follow the guide mentioned [Here](https://github.com/braheezy/catppuccin-gtk-rpm#usage)

**Comment by mainrs** [comment]
This does not work for me. There is no `gresource.xml` file in the original catppuccin theme zip files downloaded from the gtk github repository.

**Comment by rubyowo** [comment]
@mainrs if you *read* the readme that npv12 sent, you'll know that you have to compile it manually
i'll make sure to add this into this repo's readme
