### ISSUE TITLE
1.0.0-rc3 colors are very different from 0.7.5 colors

### ISSUE THREAD

**Issue by txtsd** [catppuccin/gtk#214]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe the bug.

The 1.x colors are SO different. Even the blackness tweak is different.
The Mocha colors (which is what I use) have become much brighter.
I've attached screenshots of 0.7.5 and 1.0.0-rc3 versions in both, default and black.

### Attach screenshots.

0.7.5 Mocha
![2024-05-21-13:10:58:20:625023281-590x457_grim](https://github.com/catppuccin/gtk/assets/768728/860264a7-dc2f-4803-81d0-c46781506794)

1.0.0-rc3 Mocha
![2024-05-21-13:11:08:20:875786673-590x457_grim](https://github.com/catppuccin/gtk/assets/768728/3a5eccb0-8b53-4b78-9823-1487449a4385)

0.7.5 Mocha Black
![2024-05-21-13:11:03:20:444851872-590x457_grim](https://github.com/catppuccin/gtk/assets/768728/54e90de6-e5a6-485e-b46b-f9df95170146)

1.0.0-rc3 Mocha Black
![2024-05-21-13:11:12:20:288215326-590x457_grim](https://github.com/catppuccin/gtk/assets/768728/02ec6325-2709-42ce-a360-a73ffb766fa8)

---

0.7.5 Macchiato
![2024-05-21-18:40:48:20:046323730-608x457_grim](https://github.com/catppuccin/gtk/assets/768728/7eda1a1f-f72b-476c-81d6-119b19ec3efc)

1.0.0-rc3 Macchiato
![2024-05-21-18:40:57:20:397322554-608x457_grim](https://github.com/catppuccin/gtk/assets/768728/ccdac538-05d5-4bf7-8678-089480461728)

0.7.5 Macchiato Black
![2024-05-21-18:40:50:20:882890387-608x457_grim](https://github.com/catppuccin/gtk/assets/768728/7546c26d-f3e6-4748-9ccd-16397dbe63ce)

1.0.0-rc3 Macchiato Black
![2024-05-21-18:40:59:20:037584042-608x457_grim](https://github.com/catppuccin/gtk/assets/768728/091e1226-f422-4aab-b18b-a6104ddb7dad)

---

0.7.5 Latte
![2024-05-21-18:41:10:20:068945904-608x457_grim](https://github.com/catppuccin/gtk/assets/768728/3c2753b8-559a-4a4d-a690-8aaea1f2b2c6)

1.0.0-rc3 Latte
![2024-05-21-18:41:15:20:493880513-608x457_grim](https://github.com/catppuccin/gtk/assets/768728/a43da3df-e591-497d-b7d5-deae5bf0c3f2)

0.7.5 Latte Black
![2024-05-21-18:41:11:20:841667838-608x457_grim](https://github.com/catppuccin/gtk/assets/768728/ae4be204-459d-45b4-ad23-95535ad1c1ea)

1.0.0-rc3 Latte Black
![2024-05-21-18:41:16:20:707299855-608x457_grim](https://github.com/catppuccin/gtk/assets/768728/3138356e-7d30-4fa7-a85c-23ff5a0e43d4)

---

0.7.5 Frappe
![2024-05-21-18:41:21:20:429019135-608x457_grim](https://github.com/catppuccin/gtk/assets/768728/70021527-3471-4de4-9efd-1acf8910a56c)

1.0.0-rc3 Frappe
![2024-05-21-18:41:27:20:016097161-608x457_grim](https://github.com/catppuccin/gtk/assets/768728/20ec1aaa-ad43-4c86-be36-a2ba6b7c52d9)

0.7.5 Frappe Black
![2024-05-21-18:41:22:20:948467709-608x457_grim](https://github.com/catppuccin/gtk/assets/768728/5f6e87e3-f922-42e7-96a9-0c4f81e51b74)

1.0.0-rc3 Frappe Black
![2024-05-21-18:41:28:20:465060337-608x457_grim](https://github.com/catppuccin/gtk/assets/768728/3fd5862b-8d45-4e2d-aaeb-a2757ba244fa)

### How did you install the theme?

From source (Python script)

### If using GTK4, have you symlinked the "gtk-4.0" folder?

- [X] I have symlinked the `gtk-4.0` folder.

### What GNOME version are you seeing the bug on?

N/A

**Comment by nullishamy** [comment]
I'm pretty sure these get fixed in #213 (which has some palette fixes in it), but GHA is dying atm so we can't generate test artifacts :rage: 

Once that gets sorted, and we have the test artifacts, could you retest using that PR? See https://github.com/catppuccin/gtk/blob/main/CONTRIBUTING.md#running-test-builds for instructions on how to do that!

**Comment by txtsd** [comment]
I built from source to test.
It looks much better with the changes in #213.

**Comment by nullishamy** [comment]
Great! Is there anything else in particular you noticed was off about that branch?

**Comment by nullishamy** [comment]
Hello again

I released rc4 (https://github.com/catppuccin/gtk/releases/tag/v1.0.0-rc4), which should fix all of these problems. Do get back to me here if there's any outstanding issues you face!

@txtsd
