### ISSUE TITLE
flatpak install instructions

### ISSUE THREAD

**Issue by isabelroses** [catppuccin/gtk#217]
### Is there an existing issue outlining your improvement?

- [X] I have searched the existing issues and my improvement has not been raised yet.

### What would you like to see added and/or changed?

Readd the old https://github.com/catppuccin/gtk/tree/v0.7.5?tab=readme-ov-file#for-flatpak-users

**Comment by nullishamy** [comment]
Opted not to add the flatpak instructions in the new README because it is frequently out of date, and we do not maintain it. With the install script now available, don't see a reason to keep this old cruft around?

**Comment by isabelroses** [comment]
> we do not maintain it

The previous flatpak instructions were not about an installable but giving flatpak access to the themes dir.

**Comment by nullishamy** [comment]
Oh, I see. We could add it back, sure.

**Comment by sgoudham** [comment]
> Opted not to add the flatpak instructions in the new README because it is frequently out of date, and we do not maintain it.

If we're going to add flatpak instructions into the README again, let's make it explicit that we did not create a flatpak theme and do not maintain it.

**Comment by somerand0mcat** [comment]
> If we're going to add flatpak instructions into the README again, let's make it explicit that we did not create a flatpak theme and do not maintain it.

maybe you should put a warn on the flatpak instructions about that when flatpak is added back

**Comment by somerand0mcat** [comment]
> Oh, I see. We could add it back, sure.

so i could make a pr that brings flatpak back?

**Comment by isabelroses** [comment]
> so i could make a pr that brings flatpak back?

Yes. But preferably with a warning saying we don't maintain the package. But this is how you can let flatpak see the files.

**Comment by somerand0mcat** [comment]
> Yes. But preferably with a warning saying we don't maintain the package. But this is how you can let flatpak see the files.

oh alr

**Comment by somerand0mcat** [comment]
i created a pr (#221)

**Comment by aaulia** [comment]
Not sure is this is only on my machine or not, but I had to also symlink the themes from `$HOME/.local/share/themes` to `$HOME/.themes` (just like the old documentation) and override the flatpak configuration (either by CLI or Flatseal) to expose `$HOME/.themes`. Not sure why, but without it, some application like **FontDownloader** and **Extension Manager** didn't pick up the theme.

**Comment by nullishamy** [comment]
@aaulia Hmm, interesting. We altered the guidelines / our scripts to use `~/.local/share/themes` because `~/.themes` is the older standard for themes. If we can get some more reproductions of this issue we can definitely look into adding it to the README!

**Comment by isabelroses** [comment]
@nullishamy its likely those are some older applications that still rely on the older standard and would need that symlink

**Comment by nullishamy** [comment]
Possibly, but if it isn't a widespread issue I'd rather avoid promoting old / bad practice in our README :+1:
