### ISSUE TITLE
Bug in waybar

### ISSUE THREAD

**Issue by dibusure** [catppuccin/gtk#22]
![image](https://user-images.githubusercontent.com/69085213/177864834-66a20243-df06-4ff6-b5bf-08050f819aa7.png)
It happens when i set gtk theme to Catppuccin-* (any). With other themes:
![image](https://user-images.githubusercontent.com/69085213/177865032-26c04d13-e080-4195-a217-50c99703a80a.png)

**Comment by sadrach-cl** [comment]
A new version will be released in a few days. I will close this ticket, since I only focus on the new version and I hope it will solve your problem. If not, please create a new support ticket.

Regards.
