### ISSUE TITLE
Verify that all accent zips are themed as intended

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/gtk#220]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe the issue.

https://github.com/catppuccin/gtk/blob/febd32f208ebfc0a649674b9b3b94cd21fc10fb2/build.py#L236-L251

```diff
  ctp_to_colloid = { 
-     "rosewater": "pink", 
-     "flamingo": "pink", 
      "pink": "pink", 
      "mauve": "purple", 
      "red": "red", 
-     "maroon": "red", 
      "peach": "orange", 
      "yellow": "yellow", 
      "green": "green", 
      "teal": "teal", 
-     "sky": "teal", 
-     "sapphire": "default", 
-     "blue": "default", 
+     "blue": "blue", 
-     "lavender": "default", 
 } 
```

**Context:** I don't think we should continue to publish binaries under our accent names that don't accurately reflect the Catppuccin accent. 

@nullishamy has pointed out, this command maps the Catppuccin accent to Colloid's colours, essentially meaning that we're building duplicate zips? Happy to be proven wrong on this. https://github.com/catppuccin/gtk/blob/0c3e8817da94769887c690b2211e006b287b27b1/scripts/create_theme.py#L29

**Comment by isabelroses** [comment]
They still build to the correct accent. i.e. sapphire still builds to sapphire, not to upstream "default". Seems fine to leave it as is.
