### ISSUE TITLE
Version Normal Windows Button

### ISSUE THREAD

**Issue by pewduckwei** [catppuccin/gtk#25]
hi friends, I really thank you for making a colloid theme with a catppuccin version, just a little suggestion and request can you make a normal version of the windows button also in the "release" folder?

Thank u :)

**Comment by sadrach-cl** [comment]
hello, thank you for your comment. Probably by next week. i am working on those and other compatibilities. 
Regards.

**Comment by npv12** [comment]
you can now achieve it using `python install.py mocha -a sky --tweaks normal`
