### ISSUE TITLE
Not applying theme corretly in Ubuntu 24.04

### ISSUE THREAD

**Issue by stephanlamoureux** [catppuccin/gtk#255]
### Is there an existing issue outlining your problem?

- [X] I have searched the existing issues and they do not solve my problem.

### Describe the bug.

The theme only works in a couple of random places, like the Gnome power menu and some apps like Shotwell. It doesn't apply anywhere else. I installed it using the installation script and applied the theme to the Shell and Legacy Applications with the Gnome tweak tool. 

I also added the symlinks:

I tried using the script:

`./install.py macchiato lavender --link`

and then the manual way:

`mkdir -p "${HOME}/.config/gtk-4.0" && 
ln -sf "${THEME_DIR}/gtk-4.0/assets" "${HOME}/.config/gtk-4.0/assets" &&
ln -sf "${THEME_DIR}/gtk-4.0/gtk.css" "${HOME}/.config/gtk-4.0/gtk.css" &&
ln -sf "${THEME_DIR}/gtk-4.0/gtk-dark.css" "${HOME}/.config/gtk-4.0/gtk-dark.css"`

screefetch shows that catppucin is installed as the GTK theme, but WM Theme is listed as Yaru.

### Attach screenshots.

![Screenshot from 2024-05-27 14-23-27](https://github.com/catppuccin/gtk/assets/16889593/7bff0bae-ea64-4d37-b186-35880c5ed329)
![Screenshot from 2024-05-27 14-12-02](https://github.com/catppuccin/gtk/assets/16889593/7c0fc018-57c7-44d6-8970-84fba4367599)
![Screenshot from 2024-05-27 14-08-57](https://github.com/catppuccin/gtk/assets/16889593/a30d5d0e-2e4a-4958-af50-afb02752e023)

### How did you install the theme?

From release (install.py)

### Are you running the latest release, and if not does the issue persist there?

- [X] I am running on the latest release & the issue persists there

### If using GTK4, have you symlinked the "gtk-4.0" folder?

- [X] I have symlinked the `gtk-4.0` folder.

### What GNOME version are you seeing the bug on?

GNOME Version 46.0.1

**Comment by isabelroses** [comment]
Seems like a gnome-shell issue. The best way to see if this is the case would be to install [`gnome-tweaks`](https://gitlab.gnome.org/GNOME/gnome-tweaks). This will let you see what the current shell is, and allow us to confirm whether is catppuccin or not.

**Comment by stephanlamoureux** [comment]
I applied the theme using gnome-tweaks, here is that and screenfetch:

![Screenshot from 2024-05-27 14-53-07](https://github.com/catppuccin/gtk/assets/16889593/5c5b1afc-153b-4505-a281-ac273ea1a9e6)
![Screenshot from 2024-05-27 14-52-49](https://github.com/catppuccin/gtk/assets/16889593/92a56a4c-1e64-43aa-b835-e6532d8be869)

**Comment by nullishamy** [comment]
Your shell theme doesn't seem to be applying properly, nor your GTK4 theme. Can you `ls -lah ~/.config/gtk-4.0` to show the status of the symlinks?

**Comment by stephanlamoureux** [comment]
I think this looks correct?
![Screenshot from 2024-05-27 16-53-33](https://github.com/catppuccin/gtk/assets/16889593/4f0341fe-c0ab-4944-a2d7-3dfc5eee522a)

**Comment by stephanlamoureux** [comment]
> Your shell theme doesn't seem to be applying properly, nor your GTK4 theme. Can you `ls -lah ~/.config/gtk-4.0` to show the status of the symlinks?

I think this looks correct?
![Screenshot from 2024-05-27 16-53-33](https://github.com/catppuccin/gtk/assets/16889593/4f0341fe-c0ab-4944-a2d7-3dfc5eee522a)

**Comment by stephanlamoureux** [comment]
> Seems like a gnome-shell issue. The best way to see if this is the case would be to install [`gnome-tweaks`](https://gitlab.gnome.org/GNOME/gnome-tweaks). This will let you see what the current shell is, and allow us to confirm whether is catppuccin or not.

I applied the theme using gnome-tweaks, here is that and screenfetch:

![Screenshot from 2024-05-27 14-53-07](https://github.com/catppuccin/gtk/assets/16889593/5c5b1afc-153b-4505-a281-ac273ea1a9e6)
![Screenshot from 2024-05-27 14-52-49](https://github.com/catppuccin/gtk/assets/16889593/92a56a4c-1e64-43aa-b835-e6532d8be869)

**Comment by isabelroses** [comment]
> I think this looks correct? ![Screenshot from 2024-05-27 16-53-33](https://private-user-images.githubusercontent.com/16889593/334210365-4f0341fe-c0ab-4944-a2d7-3dfc5eee522a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NDQ4NDksIm5iZiI6MTcxNjg0NDU0OSwicGF0aCI6Ii8xNjg4OTU5My8zMzQyMTAzNjUtNGYwMzQxZmUtYzBhYi00OTQ0LWEyZDctM2RmYzVlZWU1MjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDIxMTU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4MTI3MWExYzgyNDFjYTZlOTEzMDYyZjA0NjU2ZDFmYjQ4MzhjOTJkNmI2YzIyZDdlMGU1Y2RkYWRmOGE2YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S4z9_cFYQyG_c_StrMOxk2gUSGH2AhANZSus-tjPVC8)

Those look like dead symlinks to me. Bash does not have error checking for unset vars, so it looks like it symlinked to a dir that does not exist. Shall we try again with something like this. (this does assume that you have the catppuccin themes in `${HOME}/.local/share/themes`. Which is what we recommend.)
```bash
ln -sf "${HOME}/.local/share/themes/<put the catppuccin theme name here>/gtk-4.0/gtk-dark.css" "${HOME}/.config/gtk-4.0/gtk-dark.css"
ln -sf "${HOME}/.local/share/themes/<put the catppuccin theme name here>/gtk-4.0/gtk.css" "${HOME}/.config/gtk-4.0/gtk.css"
ln -sf "${HOME}/.local/share/themes/<put the catppuccin theme name here>/gtk-4.0/assets" "${HOME}/.config/gtk-4.0/assets"
```

**Comment by stephanlamoureux** [comment]
Thank you! That did the trick 🙌🏻
