### ISSUE TITLE
Use default font size?

### ISSUE THREAD

**Issue by nullchilly** [catppuccin/gtk#26]
The font size seems too small for me
![image](https://user-images.githubusercontent.com/56817415/184222449-6fa9af1a-19e9-45c6-b371-210ed88a71d0.png)
I think you should respect the system's scaling, this is the default in comparison:
![image](https://user-images.githubusercontent.com/56817415/184222731-0fbcac33-2d06-460a-ba5e-97c54ae1d2d3.png)

**Comment by sadrach-cl** [comment]
It is not a mistake, it was worked under the compact version as well as the previous versions.  I can include the normal versions, but when I have time. 

> The font size seems too small for me ![image](https://user-images.githubusercontent.com/56817415/184222449-6fa9af1a-19e9-45c6-b371-210ed88a71d0.png) I think you should respect the system's scaling, this is the default in comparison: ![image](https://user-images.githubusercontent.com/56817415/184222731-0fbcac33-2d06-460a-ba5e-97c54ae1d2d3.png)

**Comment by Cequallium** [comment]
hey any updates on this? any way to build the normal versions?
