### ISSUE TITLE
Archive repository

### ISSUE THREAD

**Issue by sgoudham** [catppuccin/gtk#262]
This repository has always been one of the most downloaded themes across the entire organisation. However, it is a _consistent_ source of pain for any contributor/maintainer that has been willing to dive into it. 

Some of this pain over the last few years has been the fact that we heavily depended on colloid and attributed a large amount of the bugs/issues to that fact. Recently, @nullishamy and others have embarked on a long, arduous and tedious journey to lessen our dependency on colloid with the noble goal of reducing the likelihood of bugs and increasing maintainability of the port in the long run.

We shipped [v1.0.0](https://github.com/catppuccin/gtk/releases/tag/v1.0.0) and [v1.0.2](https://github.com/catppuccin/gtk/releases/tag/v1.0.2) which lessens our dependency on colloid, improves performance and reworks the way the theme is applied from the ground up. We are very proud of these releases, however, we are continuing to see issues such as #260 and #258 crop up. Upon investigating further, we have realised that each distro (Fedora, Debian, Pop!_OS, etc) has implementation specific behaviour that renders our GTK theme buggy and sometimes borderline unusable. In other words, **each release has the potential to break for one set of users, while simultaneously fixing it for another set of users.** 

We thought the new build system would help solve problems and prevent the same issues from being raised again. However, **the refactor showed the us the real problem as mentioned above.**

This is an extremely difficult position to be in as maintainers and contributors have little to no confidence that bugs will stay fixed. Not to mention the extreme frustration that comes with trying debug issues raised due to lack of official debugging tools, "simple" bugs can take from hours to days to understand and raise a PR to fix, and then it needs to be tested by a wide array of configurations/distros to ensure no regressions. Ultimately, this leads to a highly unpleasant experience for maintainers.

Furthermore, based on the technical aspects of the following post - "[Restyling apps at scale - GNOME Blog](https://blogs.gnome.org/tbernard/2018/10/15/restyling-apps-at-scale/)", theming GTK is an incredibly hard undertaking and is actually discouraged by GNOME themselves as they reiterate that there is no official theming API. 

As it currently stands, we will be archiving this repository in the near future as @nullishamy feels like there is no reasonable path forward in order to make the theme consistent and usable for all. People would be encouraged to fork this repository if they would like to theme GTK. The documentation provided in this repository should be ample enough for users to gain a high level overview of how the repository is structured and can hopefully make edits themselves that work for their distro.

This issue is intended to be a place for reasonable discussion on whether this repository can continue without being archived.

**Comment by isabelroses** [comment]
Hi all.

As much as it saddens me to see this go, I can concur with @sgoudham findings. 
When trying to fix the tooltip (see https://github.com/catppuccin/gtk/pull/243), it was a miserable experience. Trying to find the `tooltip` that was breaking was not easy, and even when it got it *working*, it only worked on hyprland but not working at all on a archlinux virtual machine.

Thanks for reading, and taking the time to consider this.

**Comment by notliamsi** [comment]
GTK sucks, that's the problem.
