### ISSUE TITLE
Frappe and Macchiato inconsistencies

### ISSUE THREAD

**Issue by Scrumplex** [catppuccin/gtk#27]
[Release 0.2.7](https://github.com/catppuccin/gtk/releases/tag/v-0.2.7) added Macchiato and Frappe variants of the theme.

Some inconsistencies I noticed, while preparing the flatpak packaging for them:

- No Frappe-Lavender
- No Frappe-Mauve
- No Macchiato-Lavender
- Macchiato-Orange instead of Macchiato-Peach?

**Comment by ghostx31** [comment]
Fixed with https://github.com/catppuccin/gtk/releases/tag/v0.3.0
