### ISSUE TITLE
Gnome mines doesn't look right in this theme

### ISSUE THREAD

**Issue by ludvigng** [catppuccin/gtk#28]
Hello!

A minor nitpick perhaps, but the theme currently makes gnome mines very hard to look at:
![Skärmbild från 2022-08-17 12-31-33](https://user-images.githubusercontent.com/50339757/185098109-d298e4eb-f6a0-4a8d-a0aa-6242b8aa0342.png)
![Skärmbild från 2022-08-17 12-31-43](https://user-images.githubusercontent.com/50339757/185098134-6de4fd71-76fe-4897-b921-1ffd81f5faac.png)

Compare this to the "standard" Adwaita look:
![Skärmbild från 2022-08-17 12-33-07](https://user-images.githubusercontent.com/50339757/185098143-6d412815-3759-4a29-babc-dddcb5c66128.png)

**Comment by npv12** [comment]
It looks fine here after gnome42 support versions. If you still have this issue on newer releases, feel free to reopen the issue

**Comment by ludvigng** [comment]
Hi!

No, the issue persists. This was with the last 0.4.1 release:
![image](https://user-images.githubusercontent.com/50339757/222964399-e1dbcaba-770e-4cde-8425-88a4ea529dd5.png)

**Comment by rubyowo** [comment]
Hi! Can you please report if newer versions have fixed this issue?

**Comment by sgoudham** [comment]
Closing as issue has gone stale with no responses from authors. 

The latest release at the time of writing is https://github.com/catppuccin/gtk/releases/tag/v0.7.4. It'd be appreciated if someone could confirm if this issue is fixed in that release.

Thanks!
