### ISSUE TITLE
Strange behavior with the close window button.

### ISSUE THREAD

**Issue by MrFlish** [catppuccin/gtk#29]
Hello

The close window button is not displayed correctly (See image).
![code](https://user-images.githubusercontent.com/70275389/187050393-4e7ec96b-b063-4119-957f-21138c2fa1f0.png)

This kind of problem occurs on applications such as vscode or Thunderbird for example.

This does not happen all the time and I have not been able to find out what is causing this problem.
To solve the problem, I change the theme before reloading Catpuccin again. But this is still a band-aid.

Kind regards
Flish

**Comment by ghostx31** [comment]
Hey! Can you try updating to the latest release and let us know if the issue persists? I have not been able to reproduce your issue on either the older release or even with this release.

**Comment by sbeve72** [comment]
Facing this issue here as well

**Comment by sgoudham** [comment]
Closing as issue has gone stale with no responses from authors. 

The latest release at the time of writing is https://github.com/catppuccin/gtk/releases/tag/v0.7.4. It'd be appreciated if someone could confirm if this issue is fixed in that release.

Thanks!
