### ISSUE TITLE
Adwaita version

### ISSUE THREAD

**Issue by vanillajonathan** [catppuccin/gtk#34]
This can be themed with the [Gradiance](https://github.com/GradienceTeam/Gradience) application.

Theme can be shared at the [Gradiance Community repository](https://github.com/GradienceTeam/Community).

**Comment by nekowinston** [comment]
Hi there :wave:

We have an issue tracking Gradience on the [main repository](https://github.com/catppuccin/catppuccin) as well: https://github.com/catppuccin/catppuccin/issues/236

**Comment by ghostx31** [comment]
Since Gradience has added upstream support for Catppuccin, I'll close this.
