### ISSUE TITLE
Transparent line in chromium

### ISSUE THREAD

**Issue by noaccOS** [catppuccin/gtk#35]
Same issue as https://github.com/dracula/gtk/issues/195

![Screenshot from 2022-09-06 19-40-40](https://user-images.githubusercontent.com/24324352/188703327-933951e6-3718-4e6f-8940-389a15d43970.png)

**Comment by noaccOS** [comment]
I tried appliying the fix from dracula gtk, applying it to both the 3.0 and the 4.0 version as I was unsure
```diff
diff --git a/src/sass/gtk/_drawing-3.0.scss b/src/sass/gtk/_drawing-3.0.scss
index b9a7c99..dcdbc4a 100644
--- a/src/sass/gtk/_drawing-3.0.scss
+++ b/src/sass/gtk/_drawing-3.0.scss
@@ -102,6 +102,7 @@
     background-position: center;
     background-size: 1000% 1000%;
     color: $text;
+    border: 1px solid $button;
   }

   @if $t == hover {
diff --git a/src/sass/gtk/_drawing-4.0.scss b/src/sass/gtk/_drawing-4.0.scss
index ca6a718..021c02c 100644
--- a/src/sass/gtk/_drawing-4.0.scss
+++ b/src/sass/gtk/_drawing-4.0.scss
@@ -75,6 +75,7 @@
     box-shadow: inset 0 0 0 9999px transparent;
     background-color: $button;
     color: $text;
+    border: 1px solid $button;
   }

   @if $t == hover {
```

Then
1. Ran `./build.sh` and `./install.sh`
2. Uninstalled the system wide version of the theme
3. Unsetting and then setting again the theme both in a theme changer (the theme was changing in chromium when setting nordic or something else) and in chromium itself 

Unfortunately, the line is still there

**Comment by sadrach-cl** [comment]
This topic is based on Colloid, if Colloid applies the fix it will be done in this topic. I'm not on linux now to review in more detail.

**Comment by noaccOS** [comment]
I tried the Colloid theme and it doesn't seem affected by this issue. 
I'm only experiencing this with Dracula theme (repo version, much older than the fix) and Catppuccin gtk.

**Comment by sturlabragason-devoteam** [comment]
My understanding is that this theme is a derivative of vinceliuice/Graphite-gtk-theme where I believe the issue has been fixed. See: [https://github.com/vinceliuice/Graphite-gtk-theme/issues/62](https://github.com/vinceliuice/Graphite-gtk-theme/issues/62).

**Comment by ghostx31** [comment]
Fixed with https://github.com/catppuccin/gtk/releases/tag/v0.3.0
