### ISSUE TITLE
Dock Not Behaving Properly

### ISSUE THREAD

**Issue by ritamsaha00** [catppuccin/gtk#36]
I am using Ubuntu 22.04 with GNOME 42. When the dock is in panel mode the position of app menu icon is strange
![image](https://user-images.githubusercontent.com/69363775/189842844-b95c9a14-36ec-45b2-b9d6-8e9b532e6a14.png)
When it is not in panel mode the height of the panel is not consistent with the size of icons
![Screenshot from 2022-09-13 13-10-59](https://user-images.githubusercontent.com/69363775/189843027-38d5fd26-e47a-4e5b-a9f0-93c55c26a492.png)
If there is any solution that I don't know of, please help me

**Comment by sadrach-cl** [comment]
The theme does not replace icons. Try installing a different icon theme and changing it with gnome-tweaks

**Comment by ritamsaha00** [comment]
I think I explained it wrong. You see, when the Ubuntu dock is at the bottom position and when the panel mode is off, there's an unnecessary height. It's not the problem with icons. I tried changing the icons, but the issue remains.
![image](https://user-images.githubusercontent.com/69363775/190622095-4e722f86-66b1-4a4a-a421-8b7ea6a6dccd.png)

**Comment by AnAlligatorPear** [comment]
If you are using dash to dock, make sure you have turned off the Ubuntu Dock extension while dash to dock is on.

**Comment by ritamsaha00** [comment]
I have turned off dash to dock when using ubuntu dock and vice versa

**Comment by npv12** [comment]
Hi, can you try the latest release and check if you still have this issue?

**Comment by ritamsaha00** [comment]
Oh yes, it's working properly now.

![image](https://user-images.githubusercontent.com/69363775/213085994-1a0bcdfb-44f5-4873-bcc0-db5822dbd1e5.png)
