### ISSUE TITLE
Catpuccin theme not overriding default theme elements 

### ISSUE THREAD

**Issue by AnAlligatorPear** [catppuccin/gtk#37]
Hi, thank you for such great theme work on GTK! 

I am having an issue on 0.2.7 where catpuccin theme is being applied inconsistently on both Nautilus and Header/Title bars.

![Screenshot from 2022-09-15 13-55-19](https://user-images.githubusercontent.com/93017052/190476587-c0d1b9d3-6188-4d8f-bc7f-f7ad6a03c6ea.png)

Running Gnome 42.2, Ubuntu 22.04

**Comment by ritamsaha00** [comment]
I have a similar problem where Catppuccin doesn't override the last theme of my GNOME Extension Manager app. I am also on Ubuntu 22.04.
![Screenshot from 2022-09-15 23-41-48](https://user-images.githubusercontent.com/69363775/190478940-8a6b9ff1-e7db-42bd-b147-f9db033adfd9.png)
![Screenshot from 2022-09-15 23-44-28](https://user-images.githubusercontent.com/69363775/190479305-c0a4564d-9676-40ff-a00b-1cfa31449c0b.png)

**Comment by sadrach-cl** [comment]
Then ln -sf /CATPPUCCIN-FLAVOR-LOCATION/gtk-4.0/* ~/.config/gtk-4.0

If the folder inside ~/.config doesn't exist, create it before copying over the files

**Comment by AnAlligatorPear** [comment]
Hi @sadrach-cl , I've done the gtk-4.0.css copy over to the .config folder already based upon your previous issue response, but still not change. I am rebooting every time I make that change. Do I need to do something else?

**Comment by sadrach-cl** [comment]
Do I select catppuccin in gnome-tweaks?

Verify that the files in ~/.config/gtk-4.0

~/.config/gtk-3.0 correspond to catppuccin or are shortcuts to the files on the theme

You just have to log out, you don't need to restart.

**Comment by AnAlligatorPear** [comment]
Yes. Selected catpuccin theme in gnome-tweaks. Files in both ~/.config/gtk-3.0 and ~/.config/gtk-4.0 have been changed over. Still no change,

**Comment by sadrach-cl** [comment]
Try deleting the ~/.config/gtk-2, 3, 4 folders. Restart and should start with the gnome default theme.

Select catppuccin again.

Where do you have the theme? ~/.local/share/themes or ~/.themes?

**Comment by AnAlligatorPear** [comment]
Deleted ~/.config/gtk-3, 4 folders, restarted. Reselected Catpuccin from gnome tweaks and recopied files gtk back in .config. Still same issue. 

I have the theme in ~/.themes

**Comment by sadrach-cl** [comment]
Please install another theme other than catppuccin, a new one that has not been installed before, then select it and tell me what happens.

**Comment by AnAlligatorPear** [comment]
Hi @sadrach-cl 

I figured out the issue. The catpuccin theme could not override if the Icon pack in Tweaks was set to anything other libadwaita (default) I had it set to Yaru Dark, but once I set it to adwaita everything is now conforming. 
![Screenshot from 2022-09-21 10-47-35](https://user-images.githubusercontent.com/93017052/191537164-bb386dc6-5cc5-493b-9d05-1bc440ef8afa.png)
