### ISSUE TITLE
Theme does not have Catppuccin colors

### ISSUE THREAD

**Issue by AmitGolden** [catppuccin/gtk#39]
Hi, 
Since the update the theme looks completely off:
Before: 
![1664186156](https://user-images.githubusercontent.com/39828974/192248501-ae9edd4f-b3a6-4dcf-87bf-a9d26248e144.png)

After:
![1664186166](https://user-images.githubusercontent.com/39828974/192248559-df4330fa-dfc7-4b20-9367-6cb956678027.png)

As you can see, the new theme release does not use the Catppuccin palette.

Is this a problem with my setup or did the theme got messed up?

**Comment by kcoderhtml** [comment]
You picked Catppuccin-Mocha-Mauve in the second picture rather then Catppuccin-purple in the first one.

**Comment by ghostx31** [comment]
Fixed with https://github.com/catppuccin/gtk/releases/tag/v0.3.0
