### ISSUE TITLE
GNOME activities icon options

### ISSUE THREAD

**Issue by diorcula** [catppuccin/gtk#40]
First of all, this issue has no rush and is more like a question really

Is there an option to change the 'Activities' icon for gnome shell?

Right now there is the Apple icon, but would love to change this to the Ubuntu logo.

(this might have to do with me installing Whitesur theme from Vinceluive earlier and that it nevergot deleted, but not too sure about this)

Cheers

**Comment by ghostx31** [comment]
We don't have any logo for the `Activities` button. Are you sure you're still not using the WhiteSur theme?

**Comment by diorcula** [comment]
> We don't have any logo for the `Activities` button. Are you sure you're still not using the WhiteSur theme?

Then this must indeed be a leftover from the Whitesur theme! My apologies and i will close the comment;

(would like to see some activitie buttons tho haha 😄 )
