### ISSUE TITLE
Shell theme doesn't look quite right with gnome 43

### ISSUE THREAD

**Issue by ludvigng** [catppuccin/gtk#41]
Hello!

With the release of gnome 43, there's been a change with the addition of the quick settings replacing the old aggregate menu. This has some new theme elements that aren't rendered correctly by the theme:
![Skärmbild från 2022-10-14 18-30-54](https://user-images.githubusercontent.com/50339757/195896395-8d9c6806-0008-4ff2-847d-14e99fbd9370.png)
![Skärmbild från 2022-10-14 18-31-14](https://user-images.githubusercontent.com/50339757/195896423-0ef376f5-23f7-42d1-bdcd-1cb118330024.png)

- The arrows look detached from the buttons, which are blended into the background.
- The hover color (as seen on "Balanserad") extends beyond the arrow.
- There's no "active" color, compared to the default theme.
- The gray of the submenu (that appears when you click on one of the arrows) doesn't really match the catppuccin colors or corner rounding.
- The circular buttons for power, lock and settings are cut off by the edge of the menu.

Compare this to the default theme:
![Skärmbild från 2022-10-14 18-35-21](https://user-images.githubusercontent.com/50339757/195896864-1156cf55-e8d8-48c8-8307-33081d088ff6.png)

**Comment by Skratymir** [comment]
The files app is also broken. The folder icons aren't centered and every folder takes up a lot more space than it should. 
And for the quick settings, I found a reddit post using Gnome 43 with working themed quick settings. They created the shell theme themselves though. [Here](https://github.com/Griffith-Femto/forest-dots) is the link to their custom shell theme. It is located in the Forest/gnome-shell folder.

**Comment by ghostx31** [comment]
Fixed with https://github.com/catppuccin/gtk/releases/tag/v0.3.0
