### ISSUE TITLE
Catppuccin/gtk is looking for new maintainers!

### ISSUE THREAD

**Issue by ghostx31** [catppuccin/gtk#43]
The GTK theme is looking for new maintainers. People wiling to help out with the repository can read [this discussion](https://github.com/catppuccin/gtk/discussions/42) to understand the current situation of development and how we want the future development of this port to continue. 

Of course, suggestions are always welcome. Looking forward to new contributors!

**Comment by kcoderhtml** [comment]
I would love to help but don't have discord could I still help?

**Comment by ghostx31** [comment]
Sure feel free to help around with this!

The only reason I mentioned discord is so that contributors can have synchronous communication with each other and since our previous maintainer had explained some part of the build process in the discord thread. So it would be cool if you can make a discord but it's not strict requirement. Whatever you're comfortable with!

**Comment by kcoderhtml** [comment]
Thanks!

**Comment by ghostx31** [comment]
Yes sure! Feel free to ask around on the discussion I've opened :)

**Comment by ghostx31** [comment]
I guess I should just close this now since the theme has been updated. People willing to work can of course still step forward and reach out.
