### ISSUE TITLE
Theme does not work for all system apps

### ISSUE THREAD

**Issue by SpyderGamer** [catppuccin/gtk#46]
So the theme works well with most of my system (Window borders, panels and some apps etc). But for some other applications, the theme is not being used, why is that the case?

When I downloaded the theme, I grabbed the Catppuccin Mocha Mauve theme from the releases section and extracted it to `~/.themes`.

**Here is the issue should look like:**
![image](https://user-images.githubusercontent.com/85440857/201699860-210a9be4-eb4c-45e1-ab7d-d85ccfbcf23e.png)
The one on the left is using the correct theme, but the one on the right is not.

**System:**
- Linux Mint 21 Cinnamon
- Cinnamon Version: 5.4.12

**Comment by diogogmatos** [comment]
Hey!
I had a similar problem on my Manjaro-Gnome rice. This worked for me:

Check your **gnome-extensions** by opening the "Extensions" app and look for one called `Legacy (GTK3) Theme Scheme Auto Switcher` (see screenshot bellow). If it is enabled (which I believe it is by default) turn it off.

Let me know if it worked!

P.s. Also make sure that you have enabled both the _Shell_ theme and the _Legacy Applications_ theme on **gnome-tweaks**.

**Extension:**

![image](https://user-images.githubusercontent.com/80540164/202170597-bff087fb-5389-4f2c-a1db-c1f2d15544a7.png)

**Comment by SpyderGamer** [comment]
> Hey! I had a similar problem on my Manjaro-Gnome rice. This worked for me:
> 
> Check your **gnome-extensions** by opening the "Extensions" app and look for one called `Legacy (GTK3) Theme Scheme Auto Switcher` (see screenshot bellow). If it is enabled (which I believe it is by default) turn it off.
> 
> Let me know if it worked!
> 
> P.s. Also make sure that you have enabled both the _Shell_ theme and the _Legacy Applications_ theme on **gnome-tweaks**.
> 
> **Extension:**
> 
> ![image](https://user-images.githubusercontent.com/80540164/202170597-bff087fb-5389-4f2c-a1db-c1f2d15544a7.png)

Alright thanks! I will give that a shot.

**Comment by SpyderGamer** [comment]
> Hey! I had a similar problem on my Manjaro-Gnome rice. This worked for me:
> 
> Check your **gnome-extensions** by opening the "Extensions" app and look for one called `Legacy (GTK3) Theme Scheme Auto Switcher` (see screenshot bellow). If it is enabled (which I believe it is by default) turn it off.
> 
> Let me know if it worked!
> 
> P.s. Also make sure that you have enabled both the _Shell_ theme and the _Legacy Applications_ theme on **gnome-tweaks**.
> 
> **Extension:**
> 
> ![image](https://user-images.githubusercontent.com/80540164/202170597-bff087fb-5389-4f2c-a1db-c1f2d15544a7.png)

Hey, I tried searching up the extension in the "Extensions" app, but I can't seem to find it.

**Comment by SpyderGamer** [comment]
**Found a way to fix this issue:**
- Just copy the theme folders over to this directory `/root/.themes`. If the `.themes` directory does not exist, create one.
- This way the root user has access to themes and therefore they will work on apps.
- *You need superuser privileges to do this task.

**Note:** In my case, the apps that were not themed correctly were the apps that required superuser privileges (such as software resources).

Hope this helps anyone :)
