### ISSUE TITLE
Update Catppuccin for Gnome 43

### ISSUE THREAD

**Issue by Nanotwerp** [catppuccin/gtk#48]
I think [these commits](https://github.com/witalihirsch/Mono-gtk-theme/search?q=gnome+43&type=commits) to the Mono GTK theme could help with updating this.

**Comment by Nanotwerp** [comment]
> Hey there!
> 
> We're currently working on getting the theme updated for Gnome 43 with the latest Colloid GTK source code. Switching over to someone other theme as base would break the existing user consistency. You can checkout the progress at [nekowinston/Colloid-gtk-theme](https://github.com/nekowinston/Colloid-gtk-theme).
> 
> We currently have Mocha and Macchiato working. Work is being on Frappe and Latte.

Nice! Thank you all so much for your hard work! By the way, I would highly recommend adding gtk-theme as a tag for this project. It would make it way more visible on Google and Github.

**Comment by rinav** [comment]
@ghostx31 Can we release the flavour which is completed?

**Comment by ghostx31** [comment]
The gtk theme has been updated on https://github.com/catppuccin/gtk/tree/feat/update-gtk branch. I just need to make the release zips and add them to a `Releases` folder but I've been recently overwhelmed with work from University and examinations. 
I'll be making the releases over the weekend and merge https://github.com/catppuccin/gtk/tree/feat/update-gtk into main.

**Comment by ghostx31** [comment]
Completed with https://github.com/catppuccin/gtk/releases/tag/v0.3.0
