### ISSUE TITLE
Wrong catppuccin colors

### ISSUE THREAD

**Issue by Spaxly** [catppuccin/gtk#52]
When installing catppuccin-mocha and catppuccin-mocha-teal, the background seems off as it looks like it is using the frappe or macchiato background. I have installed through the AUR, deleted then manually, thinking it might be a AUR issue. Catppuccin-Mocha-Teal also has the same issue as shown in the picture.
![catppuccin_gtk](https://user-images.githubusercontent.com/68564017/205468625-5d4e86bb-88f2-44da-b71e-5fb10160ff90.png)

**Comment by ghostx31** [comment]
This should be fixed with the latest release. I'll update the AUR package in a day or two to reflect the latest release as well.

**Comment by isabelincorp** [comment]
Lxappearance will always be a bit weird, but now you can tell the difference between backgrounds when selecting themes. (also all default versions of the new themes use mauve now)
![image](https://user-images.githubusercontent.com/114378481/205480780-2ee21097-81da-4711-8af8-749658107ded.png)
![image](https://user-images.githubusercontent.com/114378481/205480791-502fd4e8-5703-4ff2-a28c-8bec5136e13b.png)
![image](https://user-images.githubusercontent.com/114378481/205480800-d7bdd5ec-c58b-484d-919d-ae5003639324.png)
![image](https://user-images.githubusercontent.com/114378481/205480815-1d74e26f-9b54-49ca-80a2-e59a8db0779c.png)

**Comment by ghostx31** [comment]
The AUR package has been updated so marking this as completed.
