### ISSUE TITLE
AUR packages missing variant with "Blue" accent

### ISSUE THREAD

**Issue by DrymarchonShaun** [catppuccin/gtk#53]
Am I missing something, or do all the AUR packages lack the blue variants of the theme?

**Comment by ghostx31** [comment]
Yeah the blue colour is actually missing currently. We're currently completely reworking the theme thus some of the accents are missing. 
We're working on getting the missing accents added ASAP.

**Comment by rubyowo** [comment]
Hi there! We've updated the AUR packages, and now includes the blue accent
