### ISSUE TITLE
Curved corners in context menus don't work in dwm (as well as other wms)

### ISSUE THREAD

**Issue by JimPix1** [catppuccin/gtk#6]
Context menus have these ugly black corners as shown here
![image](https://user-images.githubusercontent.com/79943327/151848940-0c04be8b-9428-408f-accc-e68b57431325.png)
This happens on dwm with and without picom (a compositor)

**Comment by WitherCubes** [comment]
This is not only a dwm issue, it happens too with XFCE
![image](https://user-images.githubusercontent.com/72592921/151968518-c625dbf4-3a4a-4a83-acba-4c714d132d8f.png)

**Comment by JimPix1** [comment]
Yeah I've seen this problem a few times, I think it's an issue with i3 and possibly cinnamon

**Comment by quasigod-io** [comment]
This also happens on i3 using picom. I believe it's caused by the compositor not working right with them. I don't know enough about gtk themes to know how to fix it yet.

**Comment by sadrach-cl** [comment]
I thank you all for your feedback, unfortunately I am with my family sick and I can't dedicate myself to solve this promptly. Maybe during the next week. I hope for your understanding and I apologize for not responding sooner.

**Comment by WitherCubes** [comment]
Take your time, we will wait patiently. Hope your family gets well soon.

**Comment by JimPix1** [comment]
> I thank you all for your feedback, unfortunately I am with my family sick and I can't dedicate myself to solve this promptly. Maybe during the next week. I hope for your understanding and I apologize for not responding sooner.

That's fine! Take all the time you need. In the meantime I'll use another theme
If we can't find a solution we could just remove the curved corners or alternatively provide a version without them

**Comment by quasigod-io** [comment]
> I thank you all for your feedback, unfortunately I am with my family sick and I can't dedicate myself to solve this promptly. Maybe during the next week. I hope for your understanding and I apologize for not responding sooner.

I'm sorry to hear that, I hope they get well soon!

**Comment by quasigod-io** [comment]
A temporary fix I'm using for this is creating a file at ~/.config/gtk-3.0/gtk.css and adding 

decoration, window, window.background, window.titlebar, * {
border-radius: 0px;
}

This should remove the rounded corners from any gtk apps and dialogs.

**Comment by sadrach-cl** [comment]
Hi. The truth is that this is a problem that occurs with themes with rounded corners in wm like i3, qtile, spwm, etc. The solution is to add to your picom config 
"corner-radius = 12"

Regards.

**Comment by Red1922** [comment]
```css
menu,
.csd .menu,
.csd .dropdown,
.csd .context-menu {
  border-radius: 0px;
}
```
Add this to $XDG\_CONFIG\_HOME/gtk-3.0/gtk.css.
Some options might be redundant so please correct me if there is something that can be removed.
This snippet removes only the curved corners of context and drop down menus. Preserving the Roundness of other element. The other gtk.css solution provided a few threads above removes the roundness for all elements and it was sore to see.
