### ISSUE TITLE
Installation fails: ModuleNotFoundError: No module named 'catppuccin'

### ISSUE THREAD

**Issue by romildo** [catppuccin/gtk#60]
I am trying to install the theme using the `install.py` script, but it fails:

```console
Traceback (most recent call last):
  File "/build/source/install.py", line 10, in <module>
    from scripts.ctp_colors import ctp_colors, get_all_accent
  File "/build/source/scripts/ctp_colors.py", line 1, in <module>
    from catppuccin import Flavour
ModuleNotFoundError: No module named 'catppuccin'
```

**Comment by ghostx31** [comment]
You're supposed to install the catppuccin python library. You can do so by running `pip install -r requirements.txt` in the root of the repository directory. This step has been mentioned in the README itself.
