### ISSUE TITLE
Shell theme not working with the Blur My Shell extension on GNOME 43.1

### ISSUE THREAD

**Issue by Nanotwerp** [catppuccin/gtk#62]
Mostly everything is properly blurred except the overview, which is dark.

**Comment by ghostx31** [comment]
Do you mind sharing a screenshot of how it appears to you?

**Comment by Nanotwerp** [comment]
> Do you mind sharing a screenshot of how it appears to you?

The top image is what I get with this theme, and the bottom is what I get with the default shell theme.

![Screenshot from 2022-12-13 22-39-48](https://user-images.githubusercontent.com/17240342/207716120-72fe62e1-7d36-467e-918d-5ebe49762834.png)
![Screenshot from 2022-12-13 22-55-34](https://user-images.githubusercontent.com/17240342/207716134-779168bd-64ad-4e93-9361-9b92750c8e25.png)

**Comment by ghostx31** [comment]
@npv12 confirms that this seems to be an upstream colloid bug. 

We'll try reporting it upstream for a fix.
