### ISSUE TITLE
Selected item in Thunar has no background

### ISSUE THREAD

**Issue by opakholis** [catppuccin/gtk#64]
Hi, I've been using this theme for a long time and recently experienced a bit of background inconsistency when selecting items. You can see in the record below that the background in the type name column becomes transparent, different from the other types

Proof:
https://user-images.githubusercontent.com/49778014/208231805-3fd79ad3-1c7a-4098-b1b1-e008bcb04f7a.mp4

Current theme version:
v0.4.0

Thunar version: 
![image](https://user-images.githubusercontent.com/49778014/208232048-41fe4466-822b-47cc-99d0-a760f314bbaf.png)

**Comment by npv12** [comment]
Hi, can you try the latest release and check if you still have this issue?

**Comment by opakholis** [comment]
Unfortunately this issue still occurs in the latest version, but it will be oke if I uncheck "Show file highlight" on thunar toolbar menu.

![image](https://user-images.githubusercontent.com/49778014/214000826-ede5c764-fb47-4766-8b3d-fb2899f10875.png)

**Comment by npv12** [comment]
![Screenshot from 2023-01-23 14-40-23](https://user-images.githubusercontent.com/59979143/214002444-91b44e31-8450-45ea-b07d-4ada4a0e71fa.png)

Is this the intended behavior? I get a highlight with show file highlight option enabled

**Comment by opakholis** [comment]
Yes, can you reproduce it in List View? Icon view works fine here too

**Comment by npv12** [comment]
> Yes, can you reproduce it in List View? Icon view works fine here too

![Screenshot from 2023-01-24 09-52-22](https://user-images.githubusercontent.com/59979143/214211727-4548a3c0-9eec-4f23-88c8-dffc89896d64.png)

Also seems fine?

**Comment by RomeuG** [comment]
> Unfortunately this issue still occurs in the latest version, but it will be oke if I uncheck "Show file highlight" on thunar toolbar menu.
> 
> ![image](https://user-images.githubusercontent.com/49778014/214000826-ede5c764-fb47-4766-8b3d-fb2899f10875.png)

I also have those odd rounded borders with the black corners. Have those been fixed yet? I got the latest version and they still appear.

**Comment by opakholis** [comment]
> I also have those odd rounded borders with the black corners. Have those been fixed yet? I got the latest version and they still appear.

Hi @RomeuG, I think that the composer's duty is to make it more well-rounded. If you are using Picom, I suggest adjusting the value of `corner-radius = 12.5;` to whatever you prefer.

**Comment by opakholis** [comment]
The issue I was experiencing has been solved. I'm not sure why; perhaps it was fixed after updating to the latest version. Anyway, I need to close this thread. Thanks!🍻

**Comment by RomeuG** [comment]
Thanks for the response @opakholis, unfortunately, I am using no compositor in this case.
