### ISSUE TITLE
Gnome Files looks wrong, icons too far apart.

### ISSUE THREAD

**Issue by Araly** [catppuccin/gtk#65]
Gnome files 
![image](https://user-images.githubusercontent.com/24990801/209989013-4d34dec2-3267-414f-a114-0d55cdc5c106.png)
looks bad, everything is very far apart. As I zoom in or out, the relative space between every item also scales, so it's not just an issue at the specific zoom level of the screenshot.

Basically, files are not dense like they should, there's a lot of negative space. On other themes, the icons are either quite big, and you can't fit many items, or the icons are small and you can fit many items. With Catppuccin, the icons are small, there's not many items, and there's a lot of empty space that's unused.

Maybe it's an issue of choosing what size icon to use for the grid size ?

**Comment by npv12** [comment]
Which desktop environment do you use and what's the Nautilus version?

**Comment by Araly** [comment]
I use Gnome 43.2, and Nautilus 43.1. 
The latest Arch packages

**Comment by SpomJ** [comment]
That happens because you symlinked your gtk4 folder as described. The issue is, libadwaita uses it. As I understand, it uses theme borders + app described borders which results into this. There's a gradience theme lying somewhere in port requests, which doesn't do this.

**Comment by Araly** [comment]
> That happens because you symlinked your gtk4 folder as described. The issue is, libadwaita uses it. As I understand, it uses theme borders + app described borders which results into this. There's a gradience theme lying somewhere in port requests, which doesn't do this. Also, yeah, since gnome 43 nautilus uses libadwaita.

is there a way to install the themes without symlinking the gtk4 folder ? or do we need to wait until the gradience theme is merged ?

**Comment by npv12** [comment]
> That happens because you symlinked your gtk4 folder as described. The issue is, libadwaita uses it. As I understand, it uses theme borders + app described borders which results into this. There's a gradience theme lying somewhere in port requests, which doesn't do this. Also, yeah, since gnome 43 nautilus uses libadwaita.

No. You are supposed to be symlinking it. That's the way to theme gtk4 apps now.

**Comment by npv12** [comment]
> > That happens because you symlinked your gtk4 folder as described. The issue is, libadwaita uses it. As I understand, it uses theme borders + app described borders which results into this. There's a gradience theme lying somewhere in port requests, which doesn't do this. Also, yeah, since gnome 43 nautilus uses libadwaita.
> 
> is there a way to install the themes without symlinking the gtk4 folder ? or do we need to wait until the gradience theme is merged ?

Oh, just realised this, you are not on the latest release of catppuccin. Please update the theme.

**Comment by SpomJ** [comment]
> > That happens because you symlinked your gtk4 folder as described. The issue is, libadwaita uses it. As I understand, it uses theme borders + app described borders which results into this. There's a gradience theme lying somewhere in port requests, which doesn't do this. Also, yeah, since gnome 43 nautilus uses libadwaita.
> 
> is there a way to install the themes without symlinking the gtk4 folder ? or do we need to wait until the gradience theme is merged ?

Actually there is, just don't symlink. There's a chapter about GTK4 in install instructions.
