### ISSUE TITLE
Macchiato Lavender accent is the same color as Macchiato Blue

### ISSUE THREAD

**Issue by shadeyg56** [catppuccin/gtk#66]
I'm using the Catppuccin Macchiato GTK theme from the AUR. As can be seen in the below image of LXappearance, the Lavender option is not using the correct color. It matches the blue accent option

Lavender:
![image](https://user-images.githubusercontent.com/31134255/210039733-00c2b073-fc26-42c5-83f9-70c31d3e18e9.png)

Blue:
![image](https://user-images.githubusercontent.com/31134255/210039789-931dd217-89f8-4a21-9a92-2e6a33612c70.png)

Upon further inspection, the Sapphire color is also identical, and the Teal and Sky colors match one another. I tried using the themes directly from this repo and the issue persists.

**Comment by isabelincorp** [comment]
Hello! This is an issue with lxappearance and colloid, not us, so it can't be fixed within the preview, other than that the accent color is correct throughout other gtk apps.
![image](https://user-images.githubusercontent.com/114378481/210042689-d9c08cf2-250f-44a9-b273-6505d18ba80c.png).
