### ISSUE TITLE
Not working in Latest Manjaro Gnome

### ISSUE THREAD

**Issue by mioscape** [catppuccin/gtk#68]
Only on some GTK apps that working

**Comment by mioscape** [comment]
I install it from AUR

**Comment by rubyowo** [comment]
did you follow the stepa for GTK 4

**Comment by mioscape** [comment]
> did you follow the steps for GTK 4

I did, after reboot it keeps back to Default GTK Theme, it's all white huh

**Comment by ghostx31** [comment]
What do you mean when you say "all white"? Does it default to the Manjaro's default Gnome theme or is it a literal white? 
Also can you share what apps lose the theme? Are they all libadwaita apps? 

Also would be cool if you could check if the symlinks are still present after a reboot when you come across this issue?

**Comment by mioscape** [comment]
> did you follow the steps for GTK 4

![image](https://user-images.githubusercontent.com/43681888/213133960-b42483a6-d41f-4c3f-894d-50cb0282f6a2.png)

**Comment by ghostx31** [comment]
Seems like it cannot find the files. Are you symlinking from `/usr/share/themes`? Since the AUR package installs the theme folders in `/usr/share/themes`.

**Comment by mioscape** [comment]
> Seems like it cannot find the files. Are you symlinking from `/usr/share/themes`? Since the AUR package installs the theme folders in `/usr/share/themes`.

Not sure, how to check it?

**Comment by ghostx31** [comment]
Go to `~/.config/gtk-4.0` and type in `ls -la`. This should show where the file is symlinked from.

**Comment by mioscape** [comment]
> Go to `~/.config/gtk-4.0` and type in `ls -la`. This should show where the file is symlinked from.

Mmm, I don't think so


> drwxr-xr-x  2 ihya ihya 4096 Jan 18 19:54 .
> drwxr-xr-x 34 ihya ihya 4096 Jan 18 14:28 ..
> lrwxrwxrwx  1 ihya ihya   15 Jan 18 16:25 assets -> /gtk-4.0/assets
> -rw-r--r--  1 ihya ihya   75 Jan 18 19:54 gtk.css
> lrwxrwxrwx  1 ihya ihya   21 Jan 18 16:25 gtk-dark.css -> /gtk-4.0/gtk-dark.css
> -rw-r--r--  1 ihya ihya   47 Jan 18 19:53 settings.ini

**Comment by npv12** [comment]
> > Go to `~/.config/gtk-4.0` and type in `ls -la`. This should show where the file is symlinked from.
> 
> Mmm, I don't think so
> 
> > drwxr-xr-x  2 ihya ihya 4096 Jan 18 19:54 .
> > drwxr-xr-x 34 ihya ihya 4096 Jan 18 14:28 ..
> > lrwxrwxrwx  1 ihya ihya   15 Jan 18 16:25 assets -> /gtk-4.0/assets
> > -rw-r--r--  1 ihya ihya   75 Jan 18 19:54 gtk.css
> > lrwxrwxrwx  1 ihya ihya   21 Jan 18 16:25 gtk-dark.css -> /gtk-4.0/gtk-dark.css
> > -rw-r--r--  1 ihya ihya   47 Jan 18 19:53 settings.ini

They do not seem to be symlinked properly
Try using the script instead.

1. Clone this repo
2. pip install -r requirements.txt
3. `python install.py mocha -a green -l`
4. Then apply the new theme and check if this fixed your issue

**Comment by mioscape** [comment]
I'll try it

**Comment by mioscape** [comment]
> > > Go to `~/.config/gtk-4.0` and type in `ls -la`. This should show where the file is symlinked from.
> > 
> > 
> > Mmm, I don't think so
> > > drwxr-xr-x  2 ihya ihya 4096 Jan 18 19:54 .
> > > drwxr-xr-x 34 ihya ihya 4096 Jan 18 14:28 ..
> > > lrwxrwxrwx  1 ihya ihya   15 Jan 18 16:25 assets -> /gtk-4.0/assets
> > > -rw-r--r--  1 ihya ihya   75 Jan 18 19:54 gtk.css
> > > lrwxrwxrwx  1 ihya ihya   21 Jan 18 16:25 gtk-dark.css -> /gtk-4.0/gtk-dark.css
> > > -rw-r--r--  1 ihya ihya   47 Jan 18 19:53 settings.ini
> 
> They do not seem to be symlinked properly Try using the script instead.
> 
> 1. Clone this repo
> 2. pip install -r requirements.txt
> 3. `python install.py mocha -a green -l`
> 4. Then apply the new theme and check if this fixed your issue


![image](https://user-images.githubusercontent.com/43681888/213348657-5d0ce99f-01f5-4bb8-8052-d794092a3a81.png)

Still same, pamac theme is white default;
File manager use GTK-4 Default;
Shell is Catpuccin

**Comment by ghostx31** [comment]
Are you on the Catppuccin discord where we can make a support thread for this? I'm pretty sure you've either run the command wrong and you haven't changed the shell theme after running the install command since your accent is still blue.
