### ISSUE TITLE
Inside Selects, font color is the same as background

### ISSUE THREAD

**Issue by felixsanz** [catppuccin/gtk#69]
An image that worth 1000 words:

![1673286509](https://user-images.githubusercontent.com/6182099/211373940-15be657b-580b-4236-9b25-a0cba95c99a4.png)

**Comment by Syndrizzle** [comment]
Can you tell me what application is this? So that I can reproduce the bug

**Comment by felixsanz** [comment]
Firefox, but any select will do.

![1673788040](https://user-images.githubusercontent.com/6182099/212542408-ab838771-fc84-426b-94ba-53da8a096486.png)

**Comment by npv12** [comment]
> Firefox, but any select will do.
> 
> ![1673788040](https://user-images.githubusercontent.com/6182099/212542408-ab838771-fc84-426b-94ba-53da8a096486.png)
![Screenshot from 2023-01-18 07-21-22](https://user-images.githubusercontent.com/59979143/213061740-13f1447c-f382-4778-a86e-7a30156486b3.png)

Can you mention your DE/WM as well?

**Comment by felixsanz** [comment]
I'm using sway/wayland

**Comment by npv12** [comment]
> I'm using sway/wayland

Were you using latte version of the theme?

**Comment by felixsanz** [comment]
> > I'm using sway/wayland
> 
> Were you using latte version of the theme?

mocha, the darkest one

**Comment by npv12** [comment]
> > > I'm using sway/wayland
> > 
> > 
> > Were you using latte version of the theme?
> 
> mocha, the darkest one

Can you try again with latest release and update if it is fixed or not?

**Comment by felixsanz** [comment]
still happening :/

**Comment by Syndrizzle** [comment]
Hm i am unable to reproduce this on my end :/

**Comment by felixsanz** [comment]
no, i'm using https://github.com/catppuccin/firefox. maybe that's the issue?

**Comment by npv12** [comment]
> no, i'm using https://github.com/catppuccin/firefox. maybe that's the issue?
> 
> edit: naah, disabled it, still happening!
> 
> edit2: btw if I change to adwaita... it works fine. so it's this gtk theme indeed?

Do you have some other place where I can contact? Like joining catppuccin discord/telegram username and such? I cannot reproduce it on my end

**Comment by felixsanz** [comment]
> > no, i'm using https://github.com/catppuccin/firefox. maybe that's the issue?
> > edit: naah, disabled it, still happening!
> > edit2: btw if I change to adwaita... it works fine. so it's this gtk theme indeed?
> 
> Do you have some other place where I can contact? Like joining catppuccin discord/telegram username and such? I cannot reproduce it on my end and talking it in GitHub comments is kind of inconvenient when I would have to ask you to test a few changes

I'm on catppuccin discord, you can find me with the same name

**Comment by felixsanz** [comment]
It was an issue on my firefox / userChrome.css ! Sorry!
