### ISSUE TITLE
Cinnamon : bubbles are weird

### ISSUE THREAD

**Issue by garfieldairlines** [catppuccin/gtk#70]
I think that on Cinnamon the border radius of speech bubbles needs to be edited

![Sélection_001](https://user-images.githubusercontent.com/3239124/212831446-34a97d93-ab48-4bb0-af81-4739edbc7d04.png)

**Comment by rubyowo** [comment]
Hi there! this issue is currently from our base theme: (Colloid-GTK)[https://github.com/vinceliuice/Colloid-gtk-theme]. So could you please report this issue there as well? Thanks!

**Comment by sgoudham** [comment]
The latest release at the time of writing is [v0.7.5 (release)](https://github.com/catppuccin/gtk/releases/tag/v0.7.5). I believe this should include the upstream fix that Colloid has made and will be closing the issue.

Feel free to re-open if it hasn't!
