### ISSUE TITLE
Helvum does not display correctly.

### ISSUE THREAD

**Issue by Mikilio** [catppuccin/gtk#71]
Usually, Nodes are colorful to indicate their type. With this theme, they are all gray.

**Comment by ghostx31** [comment]
I was able to reproduce this bug in Colloid as well so seems like an upstream bug.

**Comment by npv12** [comment]
should be tracked with https://github.com/vinceliuice/Colloid-gtk-theme/issues/96

**Comment by nullishamy** [comment]
Please open a new issue with more context if this is still relevant. Our template can guide you through providing more information.  See the latest release if you want to retest on an updated version (https://github.com/catppuccin/gtk/releases/tag/v0.7.5)
