### ISSUE TITLE
install.py wrong naming scheme, fail adwaita patching.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [catppuccin/gtk#76]
```
pm  …/gtk   main !  ♥ 20:06  python install.py frappe -a lavender --tweaks rimless -l -n Catppuccin-Frappe
Recoloring to suit catppuccin theme
Recoloring accents
Recoloring all accents
Recoloring firefox
MOD: Gtkrc.sh
Mod SASS Color_Palette_default
==> Generating the 3.0 gtk.css...
==> Generating the 4.0 gtk.css...
==> Generating the gnome-shell.css...
==> Generating the cinnamon.css...
==> Generating the 3.0 gtk-Light.css...
==> Generating the 4.0 gtk-Light.css...
==> Generating the gnome-shell-Light.css...
==> Generating the cinnamon-Light.css...
==> Generating the 3.0 gtk-Dark.css...
==> Generating the 4.0 gtk-Dark.css...
==> Generating the gnome-shell-Dark.css...
==> Generating the cinnamon-Dark.css...
GNOME Shell 43.2
Rimless version! ...
Installing '/home/pm/.themes/Colloid-Dark'...

Done.
HEAD est maintenant à daec2a91 update
Failed to rename the files due to: [Errno 2] No such file or directory: '/home/pm/.themes/Catppuccin-Dark-xhdpi' -> '/home/pm/.themes/Catppuccin-Frappe-Standard-Lavender-Dark-xhdpi'
Successfully created symlinks for libadvaita

```
The script assumes that folder to rename is named `Catppuccin-Dark-xhdpi` despite, being actually `Colloid-Dark-xhdpi` and so on. The script also fails to rename without the -n argument as well.

**Comment by PoorPocketsMcNewHold** [comment]
From my testing, this does seem to fail the libadwaita patching too, regardless if you try to manually rename it or not.

**Comment by PoorPocketsMcNewHold** [comment]
A way to counter this issue, is to rename the created/linked Colloid folders, and relaunch patcher. That way, a copy of the theme will be made in the folder. One named Catppuccin-{Dark,Light}, and one named Colloid-{Dark,Light}. The libadwaita linking will still use the link via the Colloid folder, but you would still be able to only use the Catppuccin named one without fear of breaking it.

**Comment by nonetrix** [comment]
I also get this on FreeBSD
