### ISSUE TITLE
different window title buttons in cinnamon

### ISSUE THREAD

**Issue by Suppabreak** [catppuccin/gtk#8]
in cinnamon the window title buttons are generic ones and not the "mac os" looking ones

**Comment by WitherCubes** [comment]
You need to go to window manager settings and choose the Catppuccin GTK theme as your window manager theme.

**Comment by Suppabreak** [comment]
there is no window manager settings theres only a themes setting and a window titlebar setting, i have catpuccin set as the titlebar theme but its different than what is on the *actual* gtk theme

**Comment by leiswatch** [comment]
@Suppabreak You can try these (I only tested the Catppuccin-dark)
[themes.zip](https://github.com/catppuccin/gtk/files/8193387/themes.zip)
 I added macOS window buttons, and improved font size and weight in the panel + other small adjustments in the tooltips and OSDs.
