### ISSUE TITLE
idk why not working

### ISSUE THREAD

**Issue by hoopengo** [catppuccin/gtk#82]
![image](https://user-images.githubusercontent.com/51020615/227429368-ec7ac16c-5e3f-480a-bfcd-559f38fadc81.png)

**Comment by nekowinston** [comment]
Either [set up SSH](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) to clone it via SSH, or use HTTPS instead: `git clone https://github.com/catppuccin/gtk.git`
