### ISSUE TITLE
icons not viewable with light accents

### ISSUE THREAD

**Issue by kushagra-xo** [catppuccin/gtk#83]
Distro: Arch
Source: AUR

![image](https://user-images.githubusercontent.com/106916795/227521119-e8cc6a15-905b-4a9f-a140-1762e0e4c221.png)

view the open button
the icon is not viewable due the light accent.

cancel is viewable

**Comment by ghostx31** [comment]
Is this gnome 44? Gnome 43's file picker does not have icons in those buttons.

**Comment by kushagra-xo** [comment]
i think this is the xdg portal picker. i got this when using firefox under kde plasma

**Comment by rubyowo** [comment]
Hi! Can you please report if newer versions have fixed this issue?

**Comment by kushagra-xo** [comment]
i dont have the same setup anymore, please try to reproduce yourself

**Comment by sgoudham** [comment]
Closing as issue may be fixed in newer versions and author has changed setup since.
If you, the reader, have this issue - please create a [new issue](https://github.com/catppuccin/gtk/issues/new?assignees=&labels=&projects=&template=bug-report.md&title=) with a reference to this.
