### ISSUE TITLE
~/.config/gtk-4.0/gtk.css (w/ symlink) is reverting to system default after every restart

### ISSUE THREAD

**Issue by nekolifestyle** [catppuccin/gtk#84]
**Describe the bug**
The default gtk.css for gtk-4.0 is reverting after every restart. I set the proper symlink according the gtk-4.0 instructions

**Mention your distribution and your theme version**
Kubuntu 22.10 and Catppuccin-Mocha-Standard-Lavender-Dark

**Select how you installed the theme**
- [✔️ ] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.** Yes followed the instructions for this and the symlinks for assets and gtk-dark.css are unaffected

**Expected behavior**
symlinks should remain and not be overwritten after every restart

**Screenshots**
If possible, please share screenshots of the bug you've encountered. 
![Screenshot_20230324_115020](https://user-images.githubusercontent.com/60632993/227589746-da9c47e0-6f68-487d-b67d-81b29a2b55ee.png)
![Screenshot_20230324_114944](https://user-images.githubusercontent.com/60632993/227589749-7aabb827-9fc3-41a7-ae60-b2df6251c2cf.png)
![Screenshot_20230324_114922](https://user-images.githubusercontent.com/60632993/227589752-b05b367b-c306-435b-b651-d229fd81c44a.png)

**Additional context**
here the default gtk.css that keeps overwriting the symlink
[gtk.zip](https://github.com/catppuccin/gtk/files/11064609/gtk.zip)
It appears to reference a color.css thats not currently used by the current catppuccin gtk port. Which might explain why the revert is happening to begin with.

**Comment by rubyowo** [comment]
does this issue still exist for you?
