### ISSUE TITLE
The rename option doesn’t work.

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [catppuccin/gtk#87]
**Describe the bug**
The `--name` script option doesn’t rename the theme folder. It still keep the Colloid name.

**Mention your distribution and your theme version**
Latest repo version of the theme.
Fedora 37 Gnome 43

**Select how you installed the theme**
- [ ] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [✓] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**
Yes.

**Expected behavior**
Have the theme folder using the set naming scheme.

**Steps**
1. Use the script to install the theme, while using `--name` as an option. In my case : `python3 install.py frappe --name Catppuccin --accent lavender --tweaks normal -l`
```
Recoloring to suit catppuccin theme
Recoloring accents
Recoloring all accents
Recoloring firefox
MOD: Gtkrc.sh
Mod SASS Color_Palette_default
==> Generating the 3.0 gtk.css...
==> Generating the 4.0 gtk.css...
==> Generating the gnome-shell.css...
==> Generating the cinnamon.css...
==> Generating the 3.0 gtk-Light.css...
==> Generating the 4.0 gtk-Light.css...
==> Generating the gnome-shell-Light.css...
==> Generating the cinnamon-Light.css...
==> Generating the 3.0 gtk-Dark.css...
==> Generating the 4.0 gtk-Dark.css...
==> Generating the gnome-shell-Dark.css...
==> Generating the cinnamon-Dark.css...
GNOME Shell 43.2
Normal window button version! ...
Installing '/home/pm/.themes/Colloid-Dark'...

Done.
HEAD est maintenant à daec2a91 update
Successfully renamed file
Successfully created symlinks for libadvaita

``` 
(The assets generation was done on the previous commit already, so not re-generated in this instance)
2. Check if the set folder, or default ~/.themes folder have the theme folders set with the current naming scheme.

**Additional context**
Following from #76. Tested on the current repo version script.

**Comment by npv12** [comment]
Are you a member of the discord group? If so your username please?

**Comment by PoorPocketsMcNewHold** [comment]
Not at all. But I’ll rejoin it. `PoorPockets McNewHold#2546`

**Comment by PoorPocketsMcNewHold** [comment]
Was an issue with the python3 virtualenv. I’ve recreated it cleanly to fix it.
