### ISSUE TITLE
[Feature Request] 'Rim' with colors for focused windows as a --tweaks option

### ISSUE THREAD

**Issue by Teque9** [catppuccin/gtk#88]
I don't know if you work with this other catppuccin theme: https://github.com/Fausto-Korpsvart/Catppuccin-GTK-Theme but I really like the colored orange border that some of those themes have. 

Is it possible to add a 'rim' option to this theme that follows the color? Like frappe green so a green border etc etc? Displayed around the focused windows?

**Comment by ghostx31** [comment]
We don't modify anything from the [Colloid GTK theme](https://github.com/vinceliuice/Colloid-gtk-theme/) except the colour definitions to match Catppuccin. So to add border colours, it would need to exist in Colloid itself for us to support it.
