### ISSUE TITLE
Nemo and Thunar dialog being transparent on v0.4.3

### ISSUE THREAD

**Issue by sakarie9** [catppuccin/gtk#89]
**Describe the bug**

On v0.4.1, Nemo dialog shows like this
![图片](https://user-images.githubusercontent.com/20642596/230825252-bd24d16f-f029-4e84-a610-2e46efef1a19.png)

But v0.4.3 like this
![图片](https://user-images.githubusercontent.com/20642596/230825291-ca97a0a0-7d2c-4964-bdfe-ee0ee436cc8d.png)

The background of the dialog is completely transparent, which is obviously not normal behavior

Tried Thunar and Nemo, both got transparent on v0.4.3, but nautilus works fine

**Mention your distribution and your theme version**

- Arch Linux 6.2.10
- Hyprland latest git
- Catppuccin-Frappe-Standard-Pink-Dark v0.4.3
- Nemo 5.6.4
- Thunar 4.18.4

**Select how you installed the theme**
- [x] GitHub Releases
- [x] AUR package (tried both)
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)? **This is not applicable for users who have installed the theme with the Nixpkg.**
yes

**Expected behavior**
Dialog of Thunar or Nemo not transparent

**Comment by Tomkoid** [comment]
Having the same issue on Hyprland.

**Comment by chuckdotsvg** [comment]
I've experienced that also with xournalpp, blueman, and webcord dialogs. I think it's related to colloid, as I've checked out that also their theme has this bug

**Comment by ItsEthra** [comment]
Also happens with Geary email client, any possible fix?

**Comment by quadbyte** [comment]
This was fixed in colloid recently
https://github.com/vinceliuice/Colloid-gtk-theme/pull/135/commits/13947b2ba1437dbf3884ae54ab81a4d633b90e7f

**Comment by revsuine** [comment]
> This was fixed in colloid recently [vinceliuice/Colloid-gtk-theme@13947b2](https://github.com/vinceliuice/Colloid-gtk-theme/commit/13947b2ba1437dbf3884ae54ab81a4d633b90e7f)

Can this fix be merged with the Catppuccin version? Some LibreOffice popups are unreadable for me

**Comment by dangooddd** [comment]
Can reproduce, issue appears only on hyprland, but hyprland maintainer says that its not compositor issue

**Comment by sakarie9** [comment]
I've created a fork with the fix merged as a temporary workaround. You can try it [Here](https://github.com/sakarie9/gtk/releases/tag/v0.7.2.1)

**Comment by sakarie9** [comment]
> Got strange dark line below top border on some apps dialogs with your fork (cant open issue on your repo, so report it here) 

Yes, same here. And the corners below look strange to me. I'm not sure if it's due to the patch's side effects or other unresolved issues, but at least it's not transparent.

**Comment by nullishamy** [comment]
Closing as resolved. We have updated so this should work, as indicated by the functional fork. Please open another report if this is not fixed on our latest release, 0.7.5 (https://github.com/catppuccin/gtk/releases/tag/v0.7.5)
