### ISSUE TITLE
Inconsistent Naming in index.theme

### ISSUE THREAD

**Issue by DrymarchonShaun** [catppuccin/gtk#90]
**Describe the bug**
Currently the name for all theme variants inside `/usr/share/themes/*/index.theme` are not consistent with the name of the theme's folder, so applications that get theme names from that file end up having multiple entries with the same name.

**Mention your distribution and your theme version**
Please mention your Linux distribution and the theme version you've installed.
Arch Linux
Version 0.5.0  
**Select how you installed the theme**
- [ ] GitHub Releases
- [x] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script 
- [ ] Flatpak

**Expected behavior**
The name inside `index.theme` matches the name of the folder in `/usr/share/themes/`

**Screenshots**
If possible, please share screenshots of the bug you've encountered. 

**Additional context**
Please mention any additional context that might be applicable.
This might help for context? [index_theme-list.txt](https://github.com/catppuccin/gtk/files/11225870/index_theme-list.txt)

**Comment by npv12** [comment]
should be fixed with newer updates
