### ISSUE TITLE
Gnome 44

### ISSUE THREAD

**Issue by ART3MISTICAL** [catppuccin/gtk#96]
![image](https://github.com/catppuccin/gtk/assets/68769374/dc54cb91-dd3e-4f49-8976-f9c3dc5367be)

Garuda Linux

- [x] GitHub Releases
- [ ] AUR package 
- [ ] Nixpkg
- [ ] Using the python install script
- [ ] Flatpak

Symlinked the gtk-4.0 folder

**Comment by ghostx31** [comment]
Please use the latest release. This overflow issue has been fixed in the latest release.

**Comment by ART3MISTICAL** [comment]
sorry i thought i copy pasted the wrong version of the theme
