### ISSUE TITLE
POP OS!

### ISSUE THREAD

**Issue by SamueleSamarxhiu** [catppuccin/gtk#98]
Basically I extracted the .zip folder of the selected .themes folder but I cant see the theme on gnome tweaks (I also installed extension manager to load shell themes from the user directory). My gnome version is 42.5 and using gtk 3.24.33, and also latest gtk2-murrine-engine.

**Comment by rubyowo** [comment]
Hiya. Could you provide us with more info please? It'll help us debug the issue.

Though with the limited info, I'm guessing you didn't reopen tweaks after you extracted the theme.

Can you try doing it again with that additional step?

**Comment by SamueleSamarxhiu** [comment]
Hi, right now I have switched os to kubuntu so im not able to provide anything at the moment, but I guess what you wrote might be the case !

**Comment by rubyowo** [comment]
Closing this issue as the author has changed setup, if you have the same issue, try the steps above and then create a new issue.
