### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by t0msk** [catppuccin/gtk#99]
Hello,

this is very nice theme but I have issue with it, these are my appearance settings:

![image](https://github.com/catppuccin/gtk/assets/7276200/1e98901b-999d-4cbd-809b-ed3e070f4e4f)

so for shell I use Mocha and for applications I use Latte, it is nice, but there are some applications which I use (where I prefer dark mode) like Lutris, Remmina, etc.. if I go to the Settings of these applications and set dark mode nothing happens, it is still light, Catppuccin should have some "logic" that if I have Latte theme and I switch dark mode in some application it should load Mocha for that application.

I use Arch and installed it from AUR, newest packages.

**Comment by crillon** [comment]
If i get you right, you can achieve it this way:

1. In the folder where your themes are stored (`~/.themes` or `/usr/share/themes`), create two new folders;
2. Name them `Catppuccin` and `Catppuccin-dark` (with a lowercase 'd'!);
3. Move the contents of `Catppucin-Latter-Standart-Teal-Light` (light theme) to `Catppuccin`;
4. Move the contents of `Catppucin-Mocha-Standart-Teal-Dark` (dark theme) to `Catppuccin-dark`;
5. Then, in the appearance settings, select the new `Catppuccin` theme;

After that, the `prefer dark theme` setting in any application should work as intended.

**Comment by npv12** [comment]
> If i get you right, you can achieve it this way:
> 
> 1. In the folder where your themes are stored (`~/.themes` or `/usr/share/themes`), create two new folders;
> 2. Name them `Catppuccin` and `Catppuccin-dark` (with a lowercase 'd'!);
> 3. Copy or symlink the contents of `Catppucin-Latter-Standart-Teal-Light` (light theme) to `Catppuccin`;
> 4. Copy or symlink the contents of `Catppucin-Mocha-Standart-Teal-Dark` (dark theme) to `Catppuccin-dark`;
> 5. Then, in the appearance settings, select the new `Catppuccin` theme;
> 
> After that, the `prefer dark theme` setting in any application should work as intended.

Did you test it to be working? If not could you test it please? If it works then I'll add it as the default names for the themes

**Comment by crillon** [comment]
> > If i get you right, you can achieve it this way:
> > 
> > 1. In the folder where your themes are stored (`~/.themes` or `/usr/share/themes`), create two new folders;
> > 2. Name them `Catppuccin` and `Catppuccin-dark` (with a lowercase 'd'!);
> > 3. Copy or symlink the contents of `Catppucin-Latter-Standart-Teal-Light` (light theme) to `Catppuccin`;
> > 4. Copy or symlink the contents of `Catppucin-Mocha-Standart-Teal-Dark` (dark theme) to `Catppuccin-dark`;
> > 5. Then, in the appearance settings, select the new `Catppuccin` theme;
> > 
> > After that, the `prefer dark theme` setting in any application should work as intended.
> 
> Did you test it to be working? If not could you test it please? If it works then I'll add it as the default names for the themes

Yes, I tested it in Remmina and blackbox apps.

**Comment by crillon** [comment]
@npv12 Oops, yesterday I messed around with configs and themes, and after I saw this problem, I tried to enqble a dark theme in Remmina, and everything worked, and ye I'm dumb enough not to test it with the default theme names.. sorry:(

Having tested it today, I see that everything works out of the box, so it seems that the problem of @t0msk is in something else.. Mb these apps are installed via flatpak, but the theme is not applied to flatpak as written in readme.md or try to reinstalling Catppuccin.

**Comment by t0msk** [comment]
Idk what happened I have Mocha and Macchiato (both dark themes) and my apps are still light.

![image](https://github.com/catppuccin/gtk/assets/7276200/9d17b839-615f-4739-9495-111f60e0b406)

**Comment by evwltrs** [comment]
@t0msk Having the same issue as you after recent update.

**Comment by khaneliman** [comment]
I noticed i had an issue with my local config, the name of the theme seemed to have changed to a lowercase *-dark and then some of the elements seem to not be colored properly with active windows anymore.

**Comment by avanderbergh** [comment]
Found the issue:

You need to specify the name as:
```nix
gtk = {
    enable = true;
    theme = {
      name = "Catppuccin-Mocha-Standard-Pink-dark";
      package = pkgs.catppuccin-gtk.override {
        accents = ["pink"];
        variant = "mocha";
      };
    };
```

NOT

```nix
...
      name = "Catppuccin-Mocha-Standard-Pink-Dark";
...
```

I made this PR to update the docs #105
